package com.spring.controller;

import com.spring.model.Absenceeleve;
import com.spring.service.AbsenceeleveService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Absenceeleve")
@CrossOrigin("*")
public class AbsenceeleveController{
   @Autowired
   private AbsenceeleveService services;

   @GetMapping("/getAbsence/{idetudiant}")
    public List<Absenceeleve> getAbsence(@PathVariable int idetudiant) {
        try {
            List<Absenceeleve> all = services.getAbsence(idetudiant);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody Absenceeleve object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Absenceeleve> getAll() {
        try {
            List<Absenceeleve> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Absenceeleve getById(@PathVariable int id) {
        try {
            Optional<Absenceeleve> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Absenceeleve update(@PathVariable int id, @RequestBody Absenceeleve object) {
        try {
            Absenceeleve updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

