package com.spring.controller;

import com.spring.model.Absence;
import com.spring.service.AbsenceService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Absence")
@CrossOrigin("*")
public class AbsenceController{
   @Autowired
   private AbsenceService services;

   @GetMapping("/getCount/{idannee}/{idetudiant}")
    public Integer getCount(@PathVariable int idannee,@PathVariable int idetudiant) {
        try {
            Integer c = services.getCount(idannee, idetudiant);
            return c;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Absence object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Absence> getAll() {
        try {
            List<Absence> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Absence getById(@PathVariable int id) {
        try {
            Optional<Absence> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Absence update(@PathVariable int id, @RequestBody Absence object) {
        try {
            Absence updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

