package com.spring.controller;

import com.spring.model.Academy;
import com.spring.model.Academyusers;
import com.spring.model.Users;
import com.spring.model.V_demandeprof;
import com.spring.service.AcademyService;
import com.spring.service.AcademyusersService;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Academy")
@CrossOrigin("*")
public class AcademyController{
   @Autowired
   private AcademyService services;

   @Autowired
   TokenService servicetoken;
   
   @Autowired
   private AcademyusersService servicesAc;
    
   @GetMapping("/getAcademyByToken")
    public List<Academy> getDemandeProfByEcoleid(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers ac = servicesAc.findAcademyId(user.getId());
            List<Academy> list = services.findByid(ac.getId());
            return list;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }



   @GetMapping("/findAcademyById/{id}")
    public List<Academy> getAcademy(@PathVariable int id) {
        try {
            List<Academy> all = services.findByid(id);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Academy object , MultipartFile file) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Academy> getAll() {
        try {
            List<Academy> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Academy getById(@PathVariable int id) {
        try {
            Optional<Academy> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Academy update(@PathVariable int id, @RequestBody Academy object) {
        try {
            Academy updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

