package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Users;
import com.spring.service.AcademyusersService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Academyusers")
@CrossOrigin("*")
public class AcademyusersController{
   @Autowired
   private AcademyusersService services;

    @Autowired
    TokenService servicetoken;

   @GetMapping("/getAcademyId")
    public Academyusers getAcademyId(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            return services.findAcademyId(user.getId());
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody Academyusers object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Academyusers> getAll() {
        try {
            List<Academyusers> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Academyusers getById(@PathVariable int id) {
        try {
            Optional<Academyusers> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Academyusers update(@PathVariable int id, @RequestBody Academyusers object) {
        try {
            Academyusers updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

