package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Anneescolaire;
import com.spring.model.Users;
import com.spring.service.AcademyusersService;
import com.spring.service.AnneescolaireService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Anneescolaire")
@CrossOrigin("*")
public class AnneescolaireController{
   @Autowired
   private AnneescolaireService services;

   
   @Autowired
   private AcademyusersService acaUs;

    @Autowired
    TokenService servicetoken;

   @GetMapping("/findAnneeById")
    public List<Anneescolaire> getAnneescolaire(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers ac =  acaUs.findAcademyId(user.getId());
            List<Anneescolaire> all = services.getAnneeByEcoleid(ac.getAcademy_id());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Anneescolaire object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Anneescolaire> getAll() {
        try {
            List<Anneescolaire> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Anneescolaire getById(@PathVariable int id) {
        try {
            Optional<Anneescolaire> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Anneescolaire update(@PathVariable int id, @RequestBody Anneescolaire object) {
        try {
            Anneescolaire updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

