package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Calendrierscolaire;
import com.spring.model.Users;
import com.spring.service.AcademyusersService;
import com.spring.service.CalendrierscolaireService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Calendrierscolaire")
@CrossOrigin("*")
public class CalendrierscolaireController{
   @Autowired
   private CalendrierscolaireService services;

   
   @Autowired
   private AcademyusersService ac;

    @Autowired
    TokenService servicetoken;
    

    @GetMapping("/getUserAcademy")
    public Academyusers getUserAcademy(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers a =  ac.findAcademyId(user.getId());
            return a;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    @GetMapping("/findForParents/{idecole}")
    public List<Calendrierscolaire> getForParents(@PathVariable("idecole") Integer idecole) {
        try {
            List<Calendrierscolaire> all = services.forParent(idecole);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
   @GetMapping("/findEventByIdEcole")
    public List<Calendrierscolaire> getEvent(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers a =  ac.findAcademyId(user.getId());
            List<Calendrierscolaire> all = services.findByIdecole(a.getAcademy_id());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody Calendrierscolaire object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Calendrierscolaire> getAll() {
        try {
            List<Calendrierscolaire> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Calendrierscolaire getById(@PathVariable int id) {
        try {
            Optional<Calendrierscolaire> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Calendrierscolaire update(@PathVariable int id, @RequestBody Calendrierscolaire object) {
        try {
            Calendrierscolaire updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

