package com.spring.controller;

import com.spring.model.Carneteleve;
import com.spring.service.CarneteleveService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Carneteleve")
@CrossOrigin("*")
public class CarneteleveController{
   @Autowired
   private CarneteleveService services;

   @GetMapping("/findByIdetudiant/{idetudiant}")
    public List<Carneteleve> findByIdetudiant(@PathVariable int idetudiant) {
        try {
            List<Carneteleve> all = services.getIdetudiant(idetudiant);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody Carneteleve object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Carneteleve> getAll() {
        try {
            List<Carneteleve> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Carneteleve getById(@PathVariable int id) {
        try {
            Optional<Carneteleve> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Carneteleve update(@PathVariable int id, @RequestBody Carneteleve object) {
        try {
            Carneteleve updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

