package com.spring.controller;

import com.spring.model.Critereprof;
import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.service.CritereprofService;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Critereprof")
@CrossOrigin("*")
public class CritereprofController{
   @Autowired
   private CritereprofService services;

   @Autowired
   private ProfesseurService servicesProf;

    @Autowired
   TokenService servicetoken;

   @GetMapping("/getCritere")
    public List<Critereprof> getAll(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Professeur p = servicesProf.getProfesseurId(user.getId());
            List<Critereprof> all = services.getCritere(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Critereprof object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Critereprof> getAll() {
        try {
            List<Critereprof> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Critereprof getById(@PathVariable int id) {
        try {
            Optional<Critereprof> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Critereprof update(@PathVariable int id, @RequestBody Critereprof object) {
        try {
            Critereprof updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

