package com.spring.controller;

import com.spring.model.Csvmatiereclasse;
import com.spring.service.CsvmatiereclasseService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Csvmatiereclasse")
@CrossOrigin("*")
public class CsvmatiereclasseController{
   @Autowired
   private CsvmatiereclasseService services;

  /* @PostMapping("/insertCsvMatiereClasse")
    public String handleFileUpload(@RequestParam("file") MultipartFile file) {
        try {
            List<Csvmatiereclasse> csv = services.importExcelFile(file);
            services.saveDataFile(csv);
            return "success";
        } catch (IOException e) {
            e.printStackTrace();
            return "error";
        }
    }*/

   @PostMapping("/create")
    public String create(@RequestBody Csvmatiereclasse object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Csvmatiereclasse> getAll() {
        try {
            List<Csvmatiereclasse> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Csvmatiereclasse getById(@PathVariable int id) {
        try {
            Optional<Csvmatiereclasse> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Csvmatiereclasse update(@PathVariable int id, @RequestBody Csvmatiereclasse object) {
        try {
            Csvmatiereclasse updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

