package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Demandeprof;
import com.spring.model.Users;
import com.spring.model.V_ecoleclasse;
import com.spring.service.AcademyusersService;
import com.spring.service.DemandeprofService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Demandeprof")
@CrossOrigin("*")
public class DemandeprofController{
   @Autowired
   private DemandeprofService services;

 
   @Autowired
   TokenService servicetoken;

   @PostMapping("/create")
    public String create(@RequestBody Demandeprof object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Demandeprof> getAll() {
        try {
            List<Demandeprof> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Demandeprof getById(@PathVariable int id) {
        try {
            Optional<Demandeprof> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Demandeprof update(@PathVariable int id, @RequestBody Demandeprof object) {
        try {
            Demandeprof updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

