package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Ecoleclasse;
import com.spring.model.Users;
import com.spring.service.AcademyusersService;
import com.spring.service.EcoleclasseService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Ecoleclasse")
@CrossOrigin("*")
public class EcoleclasseController{
   @Autowired
   private EcoleclasseService services;

   @Autowired
   private AcademyusersService servicesAc;

    @Autowired
    TokenService servicetoken;


   @GetMapping("/getIdEcoleclasse")
    public List<Ecoleclasse> getEcoleclasseId(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers a = servicesAc.findAcademyId(user.getId());
            List<Ecoleclasse> all = services.getEcoleclasse(a.getAcademy_id());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Ecoleclasse object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Ecoleclasse> getAll() {
        try {
            List<Ecoleclasse> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Ecoleclasse getById(@PathVariable int id) {
        try {
            Optional<Ecoleclasse> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Ecoleclasse update(@PathVariable int id, @RequestBody Ecoleclasse object) {
        try {
            Ecoleclasse updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

