package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Fraisdescolarite;
import com.spring.model.Users;
import com.spring.service.AcademyusersService;
import com.spring.service.FraisdescolariteService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Fraisdescolarite")
@CrossOrigin("*")
public class FraisdescolariteController{
   @Autowired
   private FraisdescolariteService services;

   @Autowired
   private AcademyusersService servicesAc;

    @Autowired
    TokenService servicetoken;


    @GetMapping("/frais/{idecoleclasse}")
    public List<Fraisdescolarite> makaFrais(@PathVariable int idecoleclasse) {
        try {
            List<Fraisdescolarite> all = services.getFrais(idecoleclasse);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/getFrais/{idecoleclasse}")
    public List<Fraisdescolarite> getFraisScolaire(@PathVariable int idecoleclasse,@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers ac =servicesAc.findAcademyId(user.getId());
            List<Fraisdescolarite> all = services.frais(ac.getAcademy_id(), idecoleclasse);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Fraisdescolarite object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Fraisdescolarite> getAll() {
        try {
            List<Fraisdescolarite> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Fraisdescolarite getById(@PathVariable int id) {
        try {
            Optional<Fraisdescolarite> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Fraisdescolarite update(@PathVariable int id, @RequestBody Fraisdescolarite object) {
        try {
            Fraisdescolarite updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

