package com.spring.controller;

import com.spring.model.Horaireprof;
import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.service.HoraireprofService;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Horaireprof")
@CrossOrigin("*")
public class HoraireprofController{
   @Autowired
   private HoraireprofService services;

   @Autowired
   TokenService servicetoken;

   @Autowired
   ProfesseurService profService;

   @GetMapping("/findHoraireByIdprof")
    public List<Horaireprof> getHoraireProf(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<Horaireprof> all = services.getHoraireByIdprof(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Horaireprof object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Horaireprof> getAll() {
        try {
            List<Horaireprof> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Horaireprof getById(@PathVariable int id) {
        try {
            Optional<Horaireprof> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Horaireprof update(@PathVariable int id, @RequestBody Horaireprof object) {
        try {
            Horaireprof updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

