package com.spring.controller;

import com.spring.model.Media;
import com.spring.service.MediaService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Media")
@CrossOrigin("*")
public class MediaController{
   @Autowired
   private MediaService services;

   @GetMapping("/findMedia/{idecoleclasse}/{idanneescolaire}")
    public List<Media> getMedia(@PathVariable int idecoleclasse,@PathVariable int idanneescolaire) {
        try {
            List<Media> all = services.getMedia(idecoleclasse, idanneescolaire);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Media object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Media> getAll() {
        try {
            List<Media> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Media getById(@PathVariable int id) {
        try {
            Optional<Media> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Media update(@PathVariable int id, @RequestBody Media object) {
        try {
            Media updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

