package com.spring.controller;

import com.spring.model.Parentetudiant;
import com.spring.service.ParentetudiantService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Parentetudiant")
@CrossOrigin("*")
public class ParentetudiantController{
   @Autowired
   private ParentetudiantService services;


   @PostMapping("/create")
    public String create(@RequestBody Parentetudiant object) {
    try {
        services.create(object);
        return "Créée avec succès";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la création: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Parentetudiant> getAll() {
        try {
            List<Parentetudiant> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Parentetudiant getById(@PathVariable int id) {
        try {
            Optional<Parentetudiant> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Parentetudiant update(@PathVariable int id, @RequestBody Parentetudiant object) {
        try {
            Parentetudiant updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

