package com.spring.controller;

import com.spring.model.Profil;
import com.spring.service.ProfilService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Profil")
@CrossOrigin("*")
public class ProfilController{
   @Autowired
   private ProfilService services;


   @PostMapping("/create")
    public String create(@RequestBody Profil object) {
    try {
        services.create(object);
        return "Créée avec succès";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la création: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Profil> getAll() {
        try {
            List<Profil> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Profil getById(@PathVariable int id) {
        try {
            Optional<Profil> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Profil update(@PathVariable int id, @RequestBody Profil object) {
        try {
            Profil updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

