package com.spring.controller;

import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.model.V_ecoleclasse;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Professeur")
@CrossOrigin("*")
public class ProfesseurController{
   @Autowired
   private ProfesseurService services;

    @Autowired
   TokenService servicetoken;

   @GetMapping("/findProf")
    public Professeur findUserProf(@RequestHeader("Authorization") String token) throws Exception {
        Users user = servicetoken.getUser(token);
        Professeur p = services.getProfesseurId(user.getId());
        return p;
    }


   @PostMapping("/create")
    public String create(@RequestBody Professeur object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Professeur> getAll() {
        try {
            List<Professeur> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Professeur getById(@PathVariable int id) {
        try {
            Optional<Professeur> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Professeur update(@PathVariable int id, @RequestBody Professeur object) {
        try {
            Professeur updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

