package com.spring.controller;

import com.spring.model.Programmescolaire;
import com.spring.service.ProgrammescolaireService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Programmescolaire")
@CrossOrigin("*")
public class ProgrammescolaireController{
   @Autowired
   private ProgrammescolaireService services;

   @GetMapping("/chartData/{idmatiereclasse}")
    public List<Double> chartData(@PathVariable int idmatiereclasse) {
        try {
            List<Double> all = services.getStatutPrograms(idmatiereclasse);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/findByProgrammescolaire/{idmatiereclasse}")
    public List<Programmescolaire> getPorgrammeScolaire(@PathVariable int idmatiereclasse) {
        try {
            List<Programmescolaire> all = services.getByIdmatiereclasse(idmatiereclasse);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody Programmescolaire object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Programmescolaire> getAll() {
        try {
            List<Programmescolaire> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Programmescolaire getById(@PathVariable int id) {
        try {
            Optional<Programmescolaire> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Programmescolaire update(@PathVariable int id, @RequestBody Programmescolaire object) {
        try {
            Programmescolaire updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

