package com.spring.controller;

import com.spring.model.Absenceeleve;
import com.spring.model.Retardeleve;
import com.spring.service.RetardeleveService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Retardeleve")
@CrossOrigin("*")
public class RetardeleveController{
   @Autowired
   private RetardeleveService services;

   @GetMapping("/getRetard/{idetudiant}")
    public List<Retardeleve> getAbsence(@PathVariable int idetudiant) {
        try {
            List<Retardeleve> all = services.getRetard(idetudiant);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody Retardeleve object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Retardeleve> getAll() {
        try {
            List<Retardeleve> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Retardeleve getById(@PathVariable int id) {
        try {
            Optional<Retardeleve> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Retardeleve update(@PathVariable int id, @RequestBody Retardeleve object) {
        try {
            Retardeleve updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

