package com.spring.controller;

import com.spring.model.Retard;
import com.spring.service.RetardService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/Retard")
@CrossOrigin("*")
public class RetardController{
   @Autowired
   private RetardService services;

   @GetMapping("/getCount/{idannee}/{idetudiant}")
   public Integer getCount(@PathVariable int idannee,@PathVariable int idetudiant) {
       try {
           Integer c = services.getCount(idannee, idetudiant);
           return c;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }

   @PostMapping("/create")
    public String create(@RequestBody Retard object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<Retard> getAll() {
        try {
            List<Retard> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public Retard getById(@PathVariable int id) {
        try {
            Optional<Retard> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public Retard update(@PathVariable int id, @RequestBody Retard object) {
        try {
            Retard updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

