package com.spring.controller;

import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.model.V_academyannee;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;
import com.spring.service.V_academyanneeService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_academyannee")
@CrossOrigin("*")
public class V_academyanneeController{
   @Autowired
   private V_academyanneeService services;

   @Autowired
   TokenService servicetoken;

   @Autowired
   ProfesseurService profService;


   @GetMapping("/findByAcademyannee")
    public List<V_academyannee> getAcademyanneByprof(@RequestHeader("Authorization") String token) {
        try {
            
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<V_academyannee> all = services.findByProfid(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody V_academyannee object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_academyannee> getAll() {
        try {
            List<V_academyannee> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_academyannee getById(@PathVariable int id) {
        try {
            Optional<V_academyannee> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_academyannee update(@PathVariable int id, @RequestBody V_academyannee object) {
        try {
            V_academyannee updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

