package com.spring.controller;

import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.model.V_demandeajoutprof;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;
import com.spring.service.V_demandeajoutprofService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_demandeajoutprof")
@CrossOrigin("*")
public class V_demandeajoutprofController{
   @Autowired
   private V_demandeajoutprofService services;

   @Autowired
   private ProfesseurService servicesProf;

    @Autowired
   TokenService servicetoken;

   @GetMapping("/getDemande")
   public List<V_demandeajoutprof> getDemande(@RequestHeader("Authorization") String token) {
       try {
            Users user = servicetoken.getUser(token);
            Professeur p = servicesProf.getProfesseurId(user.getId());
            List<V_demandeajoutprof> all = services.getDemande(p.getId());
           return all;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }

   @PostMapping("/create")
    public String create(@RequestBody V_demandeajoutprof object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_demandeajoutprof> getAll() {
        try {
            List<V_demandeajoutprof> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_demandeajoutprof getById(@PathVariable int id) {
        try {
            Optional<V_demandeajoutprof> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_demandeajoutprof update(@PathVariable int id, @RequestBody V_demandeajoutprof object) {
        try {
            V_demandeajoutprof updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

