package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.model.V_demandeprof;
import com.spring.service.AcademyusersService;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;
import com.spring.service.V_demandeprofService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_demandeprof")
@CrossOrigin("*")
public class V_demandeprofController{
   @Autowired
   private V_demandeprofService services;

   @Autowired
   TokenService servicetoken;

   @Autowired
   ProfesseurService profService;

   
   @Autowired
   private AcademyusersService servicesAc;

    @GetMapping("/findDemandeProfByAcademy")
    public List<V_demandeprof> getDemandeProfByEcoleid(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers ac = servicesAc.findAcademyId(user.getId());
            List<V_demandeprof> list = services.getDemandeByEcoleid(ac.getAcademy_id());
            return list;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/demandeByprof")
    public List<V_demandeprof> getDemandeByprof(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<V_demandeprof> all = services.findDemandeByProf(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/demande")
    public List<V_demandeprof> getDemandeprofs(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<V_demandeprof> all = services.findDemandeNull(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody V_demandeprof object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_demandeprof> getAll() {
        try {
            List<V_demandeprof> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_demandeprof getById(@PathVariable int id) {
        try {
            Optional<V_demandeprof> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_demandeprof update(@PathVariable int id, @RequestBody V_demandeprof object) {
        try {
            V_demandeprof updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

