package com.spring.controller;

import com.spring.model.Users;
import com.spring.model.V_ecoleclasse;
import com.spring.service.TokenService;
import com.spring.service.V_ecoleclasseService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_ecoleclasse")
@CrossOrigin("*")
public class V_ecoleclasseController{
   @Autowired
   private V_ecoleclasseService services;

   @Autowired
   TokenService servicetoken;

    @GetMapping("/findByEcoleId")
    public List<V_ecoleclasse> findByEcoleid(@RequestHeader("Authorization") String token) throws Exception {
        Users user = servicetoken.getUser(token);
        //System.out.println("user    "+services.findByIduser(user.getId()).size());
        return services.findByIduser(user.getId());
    }

   @PostMapping("/create")
    public String create(@RequestBody V_ecoleclasse object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_ecoleclasse> getAll() {
        try {
            List<V_ecoleclasse> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_ecoleclasse getById(@PathVariable int id) {
        try {
            Optional<V_ecoleclasse> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_ecoleclasse update(@PathVariable int id, @RequestBody V_ecoleclasse object) {
        try {
            V_ecoleclasse updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

