package com.spring.controller;

import com.spring.model.V_edtclasse;
import com.spring.service.V_edtclasseService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_edtclasse")
@CrossOrigin("*")
public class V_edtclasseController{
   @Autowired
   private V_edtclasseService services;


   @GetMapping("/findEdt")
    public List<V_edtclasse> getEdtByClasseId(@RequestParam Integer classeId,@RequestParam Integer idannee) {
        try {
            List<V_edtclasse> all = services.edtClasse(classeId, idannee);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }



   @PostMapping("/create")
    public String create(@RequestBody V_edtclasse object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_edtclasse> getAll() {
        try {
            List<V_edtclasse> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_edtclasse getById(@PathVariable int id) {
        try {
            Optional<V_edtclasse> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_edtclasse update(@PathVariable int id, @RequestBody V_edtclasse object) {
        try {
            V_edtclasse updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

