package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Users;
import com.spring.model.V_eleveecole;
import com.spring.service.AcademyusersService;
import com.spring.service.TokenService;
import com.spring.service.V_eleveecoleService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_eleveecole")
@CrossOrigin("*")
public class V_eleveecoleController{
   @Autowired
   private V_eleveecoleService services;

   @Autowired
   private AcademyusersService acaUs;

    @Autowired
    TokenService servicetoken;


   @GetMapping("/getEleveEcole")
    public List<V_eleveecole> getEleveEcole(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers ac =  acaUs.findAcademyId(user.getId());
            List<V_eleveecole> all = services.getEleveEcole(ac.getAcademy_id());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody V_eleveecole object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_eleveecole> getAll() {
        try {
            List<V_eleveecole> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_eleveecole getById(@PathVariable int id) {
        try {
            Optional<V_eleveecole> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_eleveecole update(@PathVariable int id, @RequestBody V_eleveecole object) {
        try {
            V_eleveecole updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

