package com.spring.controller;

import com.spring.model.V_etudiantecole;
import com.spring.service.V_etudiantecoleService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_etudiantecole")
@CrossOrigin("*")
public class V_etudiantecoleController{
   @Autowired
   private V_etudiantecoleService services;

   @GetMapping("/findAnneeEnfant/{idetudiant}")
    public List<V_etudiantecole> getAnneEnfant(@PathVariable int idetudiant) {
        try {
            List<V_etudiantecole> all = services.findEnfant(idetudiant);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @GetMapping("/findByEtudiantEcole/{idecoleclasse}/{idanneescolaire}")
    public List<V_etudiantecole> getEtudiantEcole(@PathVariable int idecoleclasse,@PathVariable int idanneescolaire) {
        try {
            List<V_etudiantecole> all = services.findEtudiantecole(idecoleclasse, idanneescolaire);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody V_etudiantecole object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_etudiantecole> getAll() {
        try {
            List<V_etudiantecole> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_etudiantecole getById(@PathVariable int id) {
        try {
            Optional<V_etudiantecole> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_etudiantecole update(@PathVariable int id, @RequestBody V_etudiantecole object) {
        try {
            V_etudiantecole updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

