package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Users;
import com.spring.model.V_fraisscolarite;
import com.spring.service.AcademyusersService;
import com.spring.service.TokenService;
import com.spring.service.V_fraisscolariteService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_fraisscolarite")
@CrossOrigin("*")
public class V_fraisscolariteController{
   @Autowired
   private V_fraisscolariteService services;

     @Autowired
   private AcademyusersService servicesAc;

    @Autowired
    TokenService servicetoken;

    
   @GetMapping("/findEcolage")
    public List<V_fraisscolarite> getFrais(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Academyusers ac =servicesAc.findAcademyId(user.getId());
            List<V_fraisscolarite> all = services.getEcolage(ac.getAcademy_id());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }



   @PostMapping("/create")
    public String create(@RequestBody V_fraisscolarite object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_fraisscolarite> getAll() {
        try {
            List<V_fraisscolarite> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_fraisscolarite getById(@PathVariable int id) {
        try {
            Optional<V_fraisscolarite> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_fraisscolarite update(@PathVariable int id, @RequestBody V_fraisscolarite object) {
        try {
            V_fraisscolarite updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

