package com.spring.controller;

import com.spring.model.Horaireprof;
import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.model.V_horaireprof;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;
import com.spring.service.V_horaireprofService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.sql.Time;
import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_horaireprof")
@CrossOrigin("*")
public class V_horaireprofController{
   @Autowired
   private V_horaireprofService services;

    @Autowired
   TokenService servicetoken;

   @Autowired
   ProfesseurService profService;

   @GetMapping("/findHoraireByIdprof")
    public List<V_horaireprof> getHoraireProf(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<V_horaireprof> all = services.getHoraireProfByid(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody V_horaireprof object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_horaireprof> getAll() {
        try {
            List<V_horaireprof> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_horaireprof getById(@PathVariable int id) {
        try {
            Optional<V_horaireprof> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_horaireprof update(@PathVariable int id, @RequestBody V_horaireprof object) {
        try {
            V_horaireprof updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

