package com.spring.controller;

import com.spring.model.V_infoetudiant;
import com.spring.service.V_infoetudiantService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_infoetudiant")
@CrossOrigin("*")
public class V_infoetudiantController{
   @Autowired
   private V_infoetudiantService services;

   @GetMapping("/findInfoEtudiant/{idetudiant}")
    public List<V_infoetudiant> getInfoEtudiant(@PathVariable int idetudiant) {
        try {
            List<V_infoetudiant> all = services.getInfoEtudiant(idetudiant);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody V_infoetudiant object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_infoetudiant> getAll() {
        try {
            List<V_infoetudiant> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_infoetudiant getById(@PathVariable int id) {
        try {
            Optional<V_infoetudiant> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_infoetudiant update(@PathVariable int id, @RequestBody V_infoetudiant object) {
        try {
            V_infoetudiant updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

