package com.spring.controller;

import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.model.V_matiereclasse;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;
import com.spring.service.V_matiereclasseService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_matiereclasse")
@CrossOrigin("*")
public class V_matiereclasseController{
   @Autowired
   private V_matiereclasseService services;

   @Autowired
   TokenService servicetoken;
   
   @Autowired
   ProfesseurService profService;

   @GetMapping("/getMatiereClasse/{idecoleclasse}/{idannee}")
    public List<V_matiereclasse> getMatiereclasse(@PathVariable int idecoleclasse,@PathVariable int idannee) {
        try {
            List<V_matiereclasse> all = services.getMC(idecoleclasse, idannee);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

 
   @GetMapping("/findMatiereclasse/{idannee}")
    public List<V_matiereclasse> getMatiereclasse(@RequestHeader("Authorization") String token,@PathVariable int idannee) {
        try {
            
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<V_matiereclasse> all = services.findMatiereclasse(p.getId(), idannee);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody V_matiereclasse object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_matiereclasse> getAll() {
        try {
            List<V_matiereclasse> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_matiereclasse getById(@PathVariable int id) {
        try {
            Optional<V_matiereclasse> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_matiereclasse update(@PathVariable int id, @RequestBody V_matiereclasse object) {
        try {
            V_matiereclasse updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

