package com.spring.controller;

import com.spring.model.V_matiereandprof;
import com.spring.service.V_matiereandprofService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_matiereandprof")
@CrossOrigin("*")
public class V_matiereandprofController{
   @Autowired
   private V_matiereandprofService services;

   @GetMapping("/findByEcoleClasseId/{ecoleclasse_id}/{idannee}")
    public List<V_matiereandprof> matiereAndProf(@PathVariable int ecoleclasse_id,@PathVariable int idannee) {
        List<V_matiereandprof> list = services.readByEcoleclasse_id(ecoleclasse_id,idannee);
        return list;
    }


   @PostMapping("/create")
    public String create(@RequestBody V_matiereandprof object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_matiereandprof> getAll() {
        try {
            List<V_matiereandprof> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_matiereandprof getById(@PathVariable int id) {
        try {
            Optional<V_matiereandprof> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_matiereandprof update(@PathVariable int id, @RequestBody V_matiereandprof object) {
        try {
            V_matiereandprof updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

