package com.spring.controller;

import com.spring.model.V_noteparannee;
import com.spring.service.V_noteparanneeService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_noteparannee")
@CrossOrigin("*")
public class V_noteparanneeController{
   @Autowired
   private V_noteparanneeService services;

   @GetMapping("/getNoteModif/{idmatiereclasse}/{idtrimestre}")
   public List<V_noteparannee> getNoteModif(@PathVariable int idmatiereclasse,@PathVariable int idtrimestre) {
       try {
           List<V_noteparannee> all = services.noteModif(idmatiereclasse, idtrimestre);
           return all;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }

   @GetMapping("/getNoteEtudiant/{idannee}/{idetudiant}")
   public List<V_noteparannee> getNotesEt(@PathVariable int idannee,@PathVariable int idetudiant) {
       try {
           List<V_noteparannee> all = services.getNoteEtudiant(idannee, idetudiant);
           return all;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }



   @PostMapping("/create")
    public String create(@RequestBody V_noteparannee object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_noteparannee> getAll() {
        try {
            List<V_noteparannee> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_noteparannee getById(@PathVariable int id) {
        try {
            Optional<V_noteparannee> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_noteparannee update(@PathVariable int id, @RequestBody V_noteparannee object) {
        try {
            V_noteparannee updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

