package com.spring.controller;

import com.spring.model.Academyusers;
import com.spring.model.Users;
import com.spring.model.V_demandeprof;
import com.spring.model.V_parentetudiant;
import com.spring.service.AcademyusersService;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;
import com.spring.service.V_parentetudiantService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_parentetudiant")
@CrossOrigin("*")
public class V_parentetudiantController{
   @Autowired
   private V_parentetudiantService services;

    @Autowired
   TokenService servicetoken;


   @GetMapping("/findEnfantParent")
    public List<V_parentetudiant> getDemandeProfByEcoleid(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            List<V_parentetudiant> list = services.getEnfant(user.getId());
            return list;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody V_parentetudiant object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_parentetudiant> getAll() {
        try {
            List<V_parentetudiant> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_parentetudiant getById(@PathVariable int id) {
        try {
            Optional<V_parentetudiant> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_parentetudiant update(@PathVariable int id, @RequestBody V_parentetudiant object) {
        try {
            V_parentetudiant updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

