package com.spring.controller;

import com.spring.model.Professeur;
import com.spring.model.Users;
import com.spring.model.V_reponseoffre;
import com.spring.service.ProfesseurService;
import com.spring.service.TokenService;
import com.spring.service.V_reponseoffreService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_reponseoffre")
@CrossOrigin("*")
public class V_reponseoffreController{
   @Autowired
   private V_reponseoffreService services;

   @Autowired
   TokenService servicetoken;

   @Autowired
   ProfesseurService profService;

   @GetMapping("/offreEnvoye")
    public List<V_reponseoffre> getOffreEnvoye(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<V_reponseoffre> all = services.getOffreById(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/offre")
    public List<V_reponseoffre> getDemandeprofs(@RequestHeader("Authorization") String token) {
        try {
            Users user = servicetoken.getUser(token);
            Professeur p = profService.getProfesseurId(user.getId());
            List<V_reponseoffre> all = services.findDemandeNull(p.getId());
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


   @PostMapping("/create")
    public String create(@RequestBody V_reponseoffre object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_reponseoffre> getAll() {
        try {
            List<V_reponseoffre> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_reponseoffre getById(@PathVariable int id) {
        try {
            Optional<V_reponseoffre> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_reponseoffre update(@PathVariable int id, @RequestBody V_reponseoffre object) {
        try {
            V_reponseoffre updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

