package com.spring.controller;

import com.spring.model.V_salaireannuel;
import com.spring.service.V_salaireannuelService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_salaireannuel")
@CrossOrigin("*")
public class V_salaireannuelController{
   @Autowired
   private V_salaireannuelService services;


   @PostMapping("/create")
    public String create(@RequestBody V_salaireannuel object) {
    try {
        services.create(object);
        return "Créée avec succès";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la création: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_salaireannuel> getAll() {
        try {
            List<V_salaireannuel> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_salaireannuel getById(@PathVariable int id) {
        try {
            Optional<V_salaireannuel> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_salaireannuel update(@PathVariable int id, @RequestBody V_salaireannuel object) {
        try {
            V_salaireannuel updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

