package com.spring.controller;

import com.spring.model.V_totalsalairepannee;
import com.spring.service.V_totalsalairepanneeService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_totalsalairepannee")
@CrossOrigin("*")
public class V_totalsalairepanneeController{
   @Autowired
   private V_totalsalairepanneeService services;


   @GetMapping("/getSomme/{idanneescolaire}")
    public Double getSum(@PathVariable int idanneescolaire) {
        try {
            Double all = services.getSumm(idanneescolaire);
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PostMapping("/create")
    public String create(@RequestBody V_totalsalairepannee object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_totalsalairepannee> getAll() {
        try {
            List<V_totalsalairepannee> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_totalsalairepannee getById(@PathVariable int id) {
        try {
            Optional<V_totalsalairepannee> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_totalsalairepannee update(@PathVariable int id, @RequestBody V_totalsalairepannee object) {
        try {
            V_totalsalairepannee updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

