package com.spring.controller;

import com.spring.model.Users;
import com.spring.model.V_ecoleclasse;
import com.spring.model.V_voirdemande;
import com.spring.service.TokenService;
import com.spring.service.V_voirdemandeService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@RestController
@RequestMapping("/V_voirdemande")
@CrossOrigin("*")
public class V_voirdemandeController{
   @Autowired
   private V_voirdemandeService services;

    @Autowired
   TokenService servicetoken;


   @GetMapping("/findDemandeByIdEcole")
   public List<V_voirdemande> findByEcoleid(@RequestHeader("Authorization") String token) throws Exception {
       Users user = servicetoken.getUser(token);
       return services.findDemandeRecu(user.getId()); 
   }
   


   @PostMapping("/create")
    public String create(@RequestBody V_voirdemande object) {
    try {
        services.create(object);
        return "Cr��e avec succ�s";
    } catch (Exception e) {
        e.printStackTrace();
        return "Erreur lors de la cr�ation: " + e.getMessage();
    }
}

   @GetMapping("/find")
    public List<V_voirdemande> getAll() {
        try {
            List<V_voirdemande> all = services.read();
            return all;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @GetMapping("/find/{id}")
    public V_voirdemande getById(@PathVariable int id) {
        try {
            Optional<V_voirdemande> optional = services.readById(id);
            return  optional.get();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @PutMapping("/update/{id}")
    public V_voirdemande update(@PathVariable int id, @RequestBody V_voirdemande object) {
        try {
            V_voirdemande updated = services.update(id,object);
            return updated;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

   @DeleteMapping("/delete/{id}")
    public String delete(@PathVariable int id) {
        try {
            services.delete(id);
            return "Success";
        } catch (Exception e) {
            e.printStackTrace();
           return "Il ya erreur: "+e.getMessage();
        }
    }


}

