 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Absenceeleve;
 import java.util.*;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface AbsenceeleveRepository extends JpaRepository<Absenceeleve, Integer>  {
 @Query(value = "select * from absenceEleve where idetudiantecole = :idetudiant order by dateajout asc", nativeQuery = true)
   List<Absenceeleve> getAbsenceeleve(
       @Param("idetudiant") int idetudiant
   );
}

