 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Academy;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface AcademyRepository extends JpaRepository<Academy, Integer>  {

   @Query(value = "SELECT m.id FROM academy m WHERE m.email = :email AND m.nom = :nom", nativeQuery = true)
    List<Long> findIdByNomAndEmail(String nom, String email);

    @Query(value = "select * from academy where id=:id", nativeQuery = true)
   List<Academy> findByIdAcademy(
       @Param("id") int id
   );

}

