package com.spring.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.spring.model.Academyprof;

/*
   File generated By
   Christooj_Generation_Code
*/
@Repository
public interface AcademyprofRepository extends JpaRepository<Academyprof, Integer> {

    @Query(value = "select * from academyprof where academyid = :academyid and profid = :profid", nativeQuery = true)
    Academyprof importFunction(
        @Param("academyid") int academyid,
        @Param("profid") int profid
    );

    @Query(value = "select * from academyprof where academyid = :academyid and profid = :profid", nativeQuery = true)
    List<Academyprof> getAcademyProf(
        @Param("academyid") int academyid,
        @Param("profid") int profid
    );

    @Modifying
    @Transactional
    @Query(value = "delete from academyprof where academyid = :academyid and profid = :profid", nativeQuery = true)
    void deleteAcademyProf(
        @Param("academyid") int academyid,
        @Param("profid") int profid
    );

    List<Academyprof> findByAcademyid(Integer academyid);

    @Query(value = "select count(profid) as sum from academyprof where academyid =:academyid", nativeQuery = true)
    Integer getNbreProf(
        @Param("academyid") int academyid
    );
}
