 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.Absenceeleve;
import com.spring.model.Calendrierscolaire;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface CalendrierscolaireRepository extends JpaRepository<Calendrierscolaire, Integer>  {
   List<Calendrierscolaire> findByIdecole(int idecole);

   @Query(value = "select * from calendrierscolaire where idecole =:idecole and statut= 0", nativeQuery = true)
   List<Calendrierscolaire> getCalendrierScolaire(
       @Param("idecole") int idecole
   );
} 

