 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Carnettout;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface CarnettoutRepository extends JpaRepository<Carnettout, Integer>  {
@Query(value = "select * from carnettout where idecoleclasse=:idecoleclasse and idanneescolaire=:idanneescolaire", nativeQuery = true)
   List<Carnettout> findCarnetTout(
       @Param("idecoleclasse") int idecoleclasse,
       @Param("idanneescolaire") int idanneescolaire
   );
}

