 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
 import java.util.*;

 import com.spring.model.Classe;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface ClasseRepository extends JpaRepository<Classe, Integer>  {
   /**
    * @param startAge
    * @param endAge
    * @return
    */
    List<Classe> findByIdBetween(int startClasse, int endClasse);

    @Query(value = "SELECT * FROM classe WHERE classe = :classe" ,nativeQuery = true)
   Classe findByClasse(String classe);
}

