 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Commentaires;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface CommentairesRepository extends JpaRepository<Commentaires, Integer>  {
   List<Commentaires> findByProgrammescolaireid(Integer programmescolaireid);
}

