 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.spring.model.Csvmatiereclasse;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface CsvmatiereclasseRepository extends JpaRepository<Csvmatiereclasse, Integer>  {
      @Modifying
    @Transactional
    @Query(value = "TRUNCATE TABLE csvmatiereclasse", nativeQuery = true)
    void truncateCsvmatiereclasse();
}

