 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.spring.model.Csvnoteeleveecole;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface CsvnoteeleveecoleRepository extends JpaRepository<Csvnoteeleveecole, Integer>  {
 @Modifying
    @Transactional
    @Query(value = "TRUNCATE TABLE csvnoteeleveecole", nativeQuery = true)
    void truncateNote();
}

