 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.Academyprof;
import com.spring.model.Demandeajoutprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface DemandeajoutprofRepository extends JpaRepository<Demandeajoutprof, Integer>  {
      List<Demandeajoutprof> findByIdacademy(Integer academyid);

}

