 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

 import com.spring.model.Ecoleclasse;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface EcoleclasseRepository extends JpaRepository<Ecoleclasse, Integer>  {

   @Query(value = "SELECT * FROM ecoleclasse where idecole = :idEcole" , nativeQuery = true)
    List<Ecoleclasse> findByIdEcole(int idEcole);

}

