 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Etudiantecole;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface EtudiantecoleRepository extends JpaRepository<Etudiantecole, Integer>  {
   //List<Etudiantecole> findByIdecoleclasse(int idecoleclasse);
   @Query(value = "select * from etudiantecole where idecoleclasse = :idecoleclasse and idanneescolaire = :idanneescolaire", nativeQuery = true)
   List<Etudiantecole> findByIdecoleclasse(
       @Param("idecoleclasse") int idecoleclasse,
       @Param("idanneescolaire") int idanneescolaire
   );

   List<Etudiantecole> findByIdetudiant(Integer idetudiant);

   @Query(value = "select count(idetudiant) as somme from etudiantecole join ecoleclasse on ecoleclasse.id = etudiantecole.idecoleclasse "+ 
      "where idecole = :idecole and idanneescolaire = :idanneescolaire", nativeQuery = true)
   Integer getNbrEtudiant(
       @Param("idecole") int idecole,
       @Param("idanneescolaire") int idanneescolaire
   );
}

