 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Fraisdescolarite;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface FraisdescolariteRepository extends JpaRepository<Fraisdescolarite, Integer>  {
@Query(value = "select * from fraisdescolarite where idecole = :idecole and idecoleclasse = :idecoleclasse", nativeQuery = true)
   List<Fraisdescolarite> figetFrais(
       @Param("idecole") int idecole,
       @Param("idecoleclasse") int idecoleclasse
   );

   @Query(value = "select * from fraisdescolarite where idecoleclasse = :idecoleclasse", nativeQuery = true)
   List<Fraisdescolarite> frais(
       @Param("idecoleclasse") int idecoleclasse
   );
}

