package com.spring.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.Matiereclasse;
import com.spring.model.Verifemail;

/*
   File generated By
   Christooj_Generation_Code
*/
@Repository
public interface MatiereclasseRepository extends JpaRepository<Matiereclasse, Integer> {
    @Modifying
    @Query(value = "INSERT INTO matiere (matiere) " +
                   "SELECT DISTINCT c.matiere " +
                   "FROM csvmatiereclasse c " +
                   "LEFT JOIN matiere m ON c.matiere = m.matiere " +
                   "WHERE m.matiere IS NULL", nativeQuery = true)
    void insertMatiereFromCsv();

    @Modifying 
    @Query(value = "INSERT INTO horaireprof (profid,jourid,heuredebut,heurefin,idanneescolaire,academy,adresse,classe) " +
                   "select DISTINCT professeur.id,jours.id,csvMatiereClasse.heureDebut,csvMatiereClasse.heureFin,csvMatiereClasse.idanneescolaire,:academy,:adresse,:classe "+
                   "from csvMatiereClasse " + 
                    "join professeur on csvMatiereClasse.matricule = professeur.matricule " + 
                    "join jours on csvMatiereClasse.jour = jours.jour", nativeQuery = true)
    void insertHoraireProf(@Param("academy") String academy,@Param("adresse") String adresse,@Param("classe") String classe);

    @Modifying
    @Query(value = "INSERT INTO matiereclasse (ecoleclasse_id, matiere_id, coefficient, professeur_id, idanneescolaire) " +
                   "SELECT DISTINCT :ecoleclasseId AS ecoleId, m.id, c.coefficient, p.id, c.idanneescolaire " +
                   "FROM csvmatiereclasse c " +
                   "JOIN professeur p ON c.matricule = p.matricule " +
                   "JOIN matiere m ON c.matiere = m.matiere " +
                   "LEFT JOIN matiereclasse mc ON mc.matiere_id = m.id " +
                   "AND mc.coefficient = c.coefficient " +
                   "AND mc.ecoleclasse_id = :ecoleclasseId " +
                   "WHERE mc.matiere_id IS NULL", nativeQuery = true)
    void insertMatiereclasse(@Param("ecoleclasseId") Integer ecoleclasseId);
    
    

   
    @Modifying
    @Query(value = "INSERT INTO edtclasse (ecoleclasse_id, matiere_id, jourid, heuredebut, heurefin,idanneescolaire) " +
                   "SELECT :ecoleclasseId AS ecoleId, m.id, j.id, c.heureDebut, c.heureFin,c.idanneescolaire " +
                   "FROM csvmatiereclasse c " +
                   "JOIN matiere m ON c.matiere = m.matiere " +
                   "JOIN jours j ON j.jour = c.jour", nativeQuery = true)
    void insertEdtClasse(@Param("ecoleclasseId") Integer ecoleclasseId);
}
