 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.Matiere;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface MatiereRepository extends JpaRepository<Matiere, Integer>  {

}

