 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Media;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface MediaRepository extends JpaRepository<Media, Integer>  {
@Query(value = "select * from media where idecoleclasse = :idecoleclasse and idanneescolaire = :idanneescolaire", nativeQuery = true)
   List<Media> findMedia(
       @Param("idecoleclasse") int idecoleclasse,
       @Param("idanneescolaire") int idanneescolaire
   );
}

