 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Noteetudiantecole;
 import com.spring.model.V_demandeprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface NoteetudiantecoleRepository extends JpaRepository<Noteetudiantecole, Integer>  {
   @Modifying
    @Query(value = "INSERT INTO noteetudiantecole (idtrimestre,idmatiereclasse,idetudiant,notes)  " +
                  "select :idtrimestre,:idmatiereclasse,etudiantecole.idetudiant,csvNoteeleveecole.notes from csvNoteeleveecole  " + 
                  "join etudiantecole on etudiantecole.prefixe = csvNoteeleveecole.matricule "+
                  " where etudiantecole.idanneescolaire = :idannee", nativeQuery = true)
    void insertNote(@Param("idtrimestre") Integer idtrimestre,@Param("idmatiereclasse") Integer idmatiereclasse,@Param("idannee") Integer idannee);

    //List<Noteetudiantecole> findByIdtrimestre(Integer idtrimestre);
    @Query(value = "select * from noteetudiantecole where idtrimestre = :idtrimestre and idmatiereclasse = :idmatiereclasse", nativeQuery = true)
   List<Noteetudiantecole> findByIdtrimestre(
       @Param("idtrimestre") int idtrimestre,
       @Param("idmatiereclasse") int idmatiereclasse
   );
}

