 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.Offreecole;
 import com.spring.model.V_ecoleclasse;
 import java.util.List;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface OffreecoleRepository extends JpaRepository<Offreecole, Integer>  {
      List<Offreecole> findByEcoleId(int ecoleId);
}

