 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Professeur;
import com.spring.model.V_ecoleclasse;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface ProfesseurRepository extends JpaRepository<Professeur, Integer>  {
   Professeur findByUserId(Integer userId);

   //Professeur findByMatricule(String matricule);
   @Query(value = "select * from professeur where matricule =:matricule ", nativeQuery = true)
   Professeur findByMatricule(
       @Param("matricule") String matricule
   );
}

