 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Programmescolaire;
import com.spring.model.V_matiereclasse;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface ProgrammescolaireRepository extends JpaRepository<Programmescolaire, Integer>  {
   List<Programmescolaire> findByIdmatiereclasse(int idmatiereclasse);

   @Query(value = "select count(statut) as fait from programmescolaire where statut = 1", nativeQuery = true)
   Double done();

   @Query(value = "select count(statut) as nofait from programmescolaire where statut = 0", nativeQuery = true)
   Double notdone();
}

