 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Retard;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface RetardRepository extends JpaRepository<Retard, Integer>  {
@Query(value = "select count(id) as isa from retard where idetudiant = :idetudiant and idanneescolaire = :idannee", nativeQuery = true)
   Integer getCount(
       @Param("idannee") int idannee,
       @Param("idetudiant") int idetudiant
   );
}

