 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.Retardeleve;

import java.util.*;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface RetardeleveRepository extends JpaRepository<Retardeleve, Integer>  {
 @Query(value = "select * from retardeleve where idetudiantecole = :idetudiant order by dateretard asc", nativeQuery = true)
   List<Retardeleve> getRetardEleve(
       @Param("idetudiant") int idetudiant
   );
}

