 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Trimestre;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface TrimestreRepository extends JpaRepository<Trimestre, Integer>  {
   //List<Trimestre> findByIdecole(int idecole);

   @Query(value = "select * from trimestre where idecole= :ecoleid and idanneescolaire = :idannee", nativeQuery = true)
   List<Trimestre> findByIdecole(
       @Param("ecoleid") int ecoleid,
       @Param("idannee") int idannee
   );
}

