 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.Users;
 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface UsersRepository extends JpaRepository<Users, Integer>  {
   @Query(value = "SELECT m.id FROM users m WHERE m.email = :email AND m.mdp = :mdp" , nativeQuery = true)
   Long findIdByEmailAndMdp(@Param("email") String email, @Param("mdp") String mdp);

   Users findByEmailAndMdp(String email, String mdp);

   //Users findByEmail(String email);

   @Query(value = "select * from users where email = :email and profil_id = 4" , nativeQuery = true)
   Users findByEmail(@Param("email") String email);

   @Query(value = "select * from users where id=:id" , nativeQuery = true)
   Users getUserConnecte(@Param("id") Integer id);

}

