 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.V_academyprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_academyprofRepository extends JpaRepository<V_academyprof, Integer>  {
   List<V_academyprof> findByAcademyid(int academyid);

}

