 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.V_demandeajoutprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_demandeajoutprofRepository extends JpaRepository<V_demandeajoutprof, Integer>  {
@Query(value = "select * from v_demandeajoutprof where idprof =:idprof and statut = 0 order by dateajout;", nativeQuery = true)
   List<V_demandeajoutprof> getDemandeAjoutProf(
       @Param("idprof") int idprof
   );
}

