 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import java.util.List;

import com.spring.model.Demandeprof;
import com.spring.model.V_demandeprof;
 import com.spring.model.V_matiereandprof;
import com.spring.model.Verifemail;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_demandeprofRepository extends JpaRepository<V_demandeprof, Integer>  {
   @Query(value = "select * from v_demandeProf where professeur_id IS NULL OR professeur_id != :profId and statut = 0", nativeQuery = true)
   List<V_demandeprof> findDemandeNull(
       @Param("profId") int profId
   );

   @Query(value = "select * from v_demandeProf where professeur_id = :profid and statut= :statut", nativeQuery = true)
   List<V_demandeprof> findByProfid(
       @Param("profid") int profid,
       @Param("statut") int statut
   );

    @Query(value = "select * from v_demandeProf where academy_id = :ecoleid and statut= :statut", nativeQuery = true)
   List<V_demandeprof> findByEcoleidStatut(
       @Param("ecoleid") int ecoleid,
       @Param("statut") int statut
   );

}

