 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_ecolageparannee;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_ecolageparanneeRepository extends JpaRepository<V_ecolageparannee, Integer>  {
@Query(value = "select * from v_ecolageparannee order by idanneescolaire", nativeQuery = true)
   List<V_ecolageparannee> getV_ecolageparannees();
}

