 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_edtclasse;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_edtclasseRepository extends JpaRepository<V_edtclasse, Integer>  {
      //List<V_edtclasse> findByClasseid(Integer classeId);

      @Query(value = "select * from v_edtclasse where classeid = :classeid and idanneescolaire = :idannee order by heuredebut,heurefin", nativeQuery = true)
   List<V_edtclasse> findEdtClasseAnne(
       @Param("classeid") int classeid,
       @Param("idannee") int idannee
   );
}

