 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.V_eleveecole;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_eleveecoleRepository extends JpaRepository<V_eleveecole, Integer>  {
   List<V_eleveecole> findByIdecole(int idecole);
}

