 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_etudiantecole;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_etudiantecoleRepository extends JpaRepository<V_etudiantecole, Integer>  {
   @Query(value = "select * from v_etudiantecole where idecoleclasse = :idecoleclasse and idanneescolaire = :idanneescolaire", nativeQuery = true)
   List<V_etudiantecole> findEtudiantEcole(
       @Param("idecoleclasse") int idecoleclasse,
       @Param("idanneescolaire") int idanneescolaire
   );

   List<V_etudiantecole> findByIdetudiant(Integer idetudiant);
}

