 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

 import com.spring.model.V_fraisscolarite;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_fraisscolariteRepository extends JpaRepository<V_fraisscolarite, Integer>  {
   //List<V_fraisscolarite> findByIdecole(int idecole);

   @Query(value = "select * from v_fraisscolarite where idecole = :idecole order by classe", nativeQuery = true)
   List<V_fraisscolarite> findByIdecole(
       @Param("idecole") int idecole
   );

}

