 package com.spring.repository;

 import java.sql.Time;
import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_horaireprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_horaireprofRepository extends JpaRepository<V_horaireprof, Integer>  {
@Query(value = "select * from v_horaireprof where jour = :jour AND :debut < heurefin and :fin > heuredebut and idprof = :idprof and idanneescolaire = :idannee", nativeQuery = true)
   List<V_horaireprof> getHoraireProf(
       @Param("jour") String jour,
       @Param("debut") Time debut,
       @Param("fin") Time fin,
       @Param("idprof") int idprof,
       @Param("idannee") int idannee
   );

   @Query(value = "select * from v_horaireprof where idprof = :idprof order by jourid, heuredebut, heurefin", nativeQuery = true)
   List<V_horaireprof> findByIdprof(
       @Param("idprof") int idprof
      );

 }

  // List<V_horaireprof> findByIdprof(Integer idprof);}

