 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.V_infoetudiant;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_infoetudiantRepository extends JpaRepository<V_infoetudiant, Integer>  {
   List<V_infoetudiant> findByIdetudiant(int idetudiant);
}

