 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_matiereandprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_matiereandprofRepository extends JpaRepository<V_matiereandprof, Integer>  {
     //List<V_matiereandprof> findByecoleclasseid(int ecoleclasse_id);
 @Query(value = "select * from v_matiereandprof where ecoleclasse_id = :classeid and idanneescolaire = :idannee order by id", nativeQuery = true)
   List<V_matiereandprof> findMatiereProfClasseAnnee(
       @Param("classeid") int classeid,
       @Param("idannee") int idannee
   );
}

