 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_month;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_monthRepository extends JpaRepository<V_month, Integer>  {
   @Query(value = "select * from v_month where id = :id", nativeQuery = true)
   List<V_month> findVMonth(
       @Param("id") int id
   );
}

