 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.V_moyenne;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_moyenneRepository extends JpaRepository<V_moyenne, Integer>  {
   List<V_moyenne>  findByIdanneescolaire(Integer idanneescolaire);

}

