 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_noteparannee;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_noteparanneeRepository extends JpaRepository<V_noteparannee, Integer>  {
   @Query(value = "select * from v_noteparannee where idanneescolaire = :idannee and idetudiant = :idetudiant order by idtrimestre", nativeQuery = true)
   List<V_noteparannee> getNote(
       @Param("idannee") int idannee,
       @Param("idetudiant") int idetudiant
   );

   @Query(value = "select * from v_noteparannee where idmatiereclasse = :idmatiereclasse and idtrimestre = :idtrimestre order by idetudiant", nativeQuery = true)
   List<V_noteparannee> getNoteModif(
       @Param("idmatiereclasse") int idmatiereclasse,
       @Param("idtrimestre") int idtrimestre
   );

   
}

