 package com.spring.repository;

 import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.V_profnotinacademy;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_profnotinacademyRepository extends JpaRepository<V_profnotinacademy, Integer>  {

}

