 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.V_profilprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_profilprofRepository extends JpaRepository<V_profilprof, Integer>  {
   List<V_profilprof> findByIduser(Integer iduser);
}

