 package com.spring.repository;

 import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_reponseoffre;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_reponseoffreRepository extends JpaRepository<V_reponseoffre, Integer>  {
   @Query(value = "select * from v_reponseOffre where professeur_id IS NULL OR professeur_id != :profId", nativeQuery = true)
   List<V_reponseoffre> findOffreNull(
    @Param("profId") int profId
   );

   List<V_reponseoffre> findByProfid(int profid);

}

