 package com.spring.repository;

 import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
 import org.springframework.stereotype.Repository;

 import com.spring.model.V_salaireprof;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_salaireprofRepository extends JpaRepository<V_salaireprof, Integer>  {
   List<V_salaireprof> findByIdecole(int idecole);
}

