 package com.spring.repository;

 import java.util.List;
 
 import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.spring.model.V_totalsalairepannee;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Repository
 public interface V_totalsalairepanneeRepository extends JpaRepository<V_totalsalairepannee, Integer>  {
@Query(value = "select sum(total_final) from v_totalSalairePAnnee where idanneescolaire = :idanneescolaire group by idanneescolaire;", nativeQuery = true)
   Double getSomme(
       @Param("idanneescolaire") int idanneescolaire
   );
}

