 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Absence;
 import com.spring.repository.AbsenceRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class AbsenceService {
    private final AbsenceRepository repo;

    public Integer getCount(int idannee,int idetudiant) {
      return repo.getCount(idannee,idetudiant);
  }

    @Autowired
    public AbsenceService(AbsenceRepository rep) {
        this.repo = rep;
    }

    public Absence create(Absence object) {
       return repo.save(object);
   }


    public List<Absence> read() {
       return repo.findAll();
    }

    public Optional<Absence> readById(int id) {
       return repo.findById(id);
    }

    public Absence update(int id, Absence object) {
       try {

           Optional<Absence> optional = repo.findById(id);
           if (optional.isPresent()) {
               Absence existing = optional.get();
               existing = (Absence) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

