 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Academyprof;
 import com.spring.repository.AcademyprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class AcademyprofService {
    private final AcademyprofRepository repo;

    public Integer getNbre(int academyId) {
      return repo.getNbreProf(academyId);
  }
    
    public void remove(int academyId,int profid){
      repo.deleteAcademyProf(academyId,profid);
    }

    public Academyprof verifyAcademyProf(int academyId,int profid) {
      return repo.importFunction(academyId,profid);
  }

    public List<Academyprof> getAcademyProf(int academyId,int profid) {
      return repo.getAcademyProf(academyId,profid);
  }

    @Autowired
    public AcademyprofService(AcademyprofRepository rep) {
        this.repo = rep;
    }

    public Academyprof create(Academyprof object) {
       return repo.save(object);
   }


    public List<Academyprof> read() {
       return repo.findAll();
    }

    public Optional<Academyprof> readById(int id) {
       return repo.findById(id);
    }

    public Academyprof update(int id, Academyprof object) {
       try {

           Optional<Academyprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               Academyprof existing = optional.get();
               existing = (Academyprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

