 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Anneescolaire;
import com.spring.repository.AnneescolaireRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class AnneescolaireService {
    private final AnneescolaireRepository repo;


    public Anneescolaire getAnneescolaire(int debut,int fin,int ecoleid) {
      return repo.getIdAnneScolaire(debut,fin,ecoleid);
  }

  public List<Anneescolaire> getAnneeByEcoleid(int ecoleid) {
   return repo.findByIdecole(ecoleid);
}

    @Autowired
    public AnneescolaireService(AnneescolaireRepository rep) {
        this.repo = rep;
    }

    public Anneescolaire create(Anneescolaire object) {
       return repo.save(object);
   }


    public List<Anneescolaire> read() {
       return repo.findAll();
    }

    public Optional<Anneescolaire> readById(int id) {
       return repo.findById(id);
    }

    public Anneescolaire update(int id, Anneescolaire object) {
       try {

           Optional<Anneescolaire> optional = repo.findById(id);
           if (optional.isPresent()) {
               Anneescolaire existing = optional.get();
               existing = (Anneescolaire) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }

    public Anneescolaire AnneeeActif(Object ecole_id){
      Long id = Long.parseLong(ecole_id.toString());
      return repo.findAnneesActif(id);
    }
   
}

