 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Calendrierscolaire;
 import com.spring.repository.CalendrierscolaireRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class CalendrierscolaireService {
    private final CalendrierscolaireRepository repo;

    public List<Calendrierscolaire> forParent(int idecole) {
      return repo.getCalendrierScolaire(idecole);
   }

    @Autowired
    public CalendrierscolaireService(CalendrierscolaireRepository rep) {
        this.repo = rep;
    }

    public Calendrierscolaire create(Calendrierscolaire object) {
       return repo.save(object);
   }

   public List<Calendrierscolaire> findByIdecole(int idecole) {
      return repo.findByIdecole(idecole);
   }



    public List<Calendrierscolaire> read() {
       return repo.findAll();
    }

    public Optional<Calendrierscolaire> readById(int id) {
       return repo.findById(id);
    }

    public Calendrierscolaire update(int id, Calendrierscolaire object) {
       try {

           Optional<Calendrierscolaire> optional = repo.findById(id);
           if (optional.isPresent()) {
               Calendrierscolaire existing = optional.get();
               existing = (Calendrierscolaire) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

