 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Carnettout;
 import com.spring.repository.CarnettoutRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class CarnettoutService {
    private final CarnettoutRepository repo;

    public List<Carnettout> getCarnetTout(int idecoleclasse,int idanneescolaire) {
      return repo.findCarnetTout(idecoleclasse,idanneescolaire);
   }

    @Autowired
    public CarnettoutService(CarnettoutRepository rep) {
        this.repo = rep;
    }

    public Carnettout create(Carnettout object) {
       return repo.save(object);
   }


    public List<Carnettout> read() {
       return repo.findAll();
    }

    public Optional<Carnettout> readById(int id) {
       return repo.findById(id);
    }

    public Carnettout update(int id, Carnettout object) {
       try {

           Optional<Carnettout> optional = repo.findById(id);
           if (optional.isPresent()) {
               Carnettout existing = optional.get();
               existing = (Carnettout) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

