package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Carneteleve;
 import com.spring.repository.CarneteleveRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class CarneteleveService {
    private final CarneteleveRepository repo;

    public List<Carneteleve> getIdetudiant(int idetudiant) {
      return repo.findByIdetudiant(idetudiant);
   }

    @Autowired
    public CarneteleveService(CarneteleveRepository rep) {
        this.repo = rep;
    }

    public Carneteleve create(Carneteleve object) {
       return repo.save(object);
   }


    public List<Carneteleve> read() {
       return repo.findAll();
    }

    public Optional<Carneteleve> readById(int id) {
       return repo.findById(id);
    }

    public Carneteleve update(int id, Carneteleve object) {
       try {

           Optional<Carneteleve> optional = repo.findById(id);
           if (optional.isPresent()) {
               Carneteleve existing = optional.get();
               existing = (Carneteleve) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

