 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Classeniveau;
 import com.spring.repository.ClasseniveauRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class ClasseniveauService {
    private final ClasseniveauRepository repo;

    @Autowired
    public ClasseniveauService(ClasseniveauRepository rep) {
        this.repo = rep;
    }

    public Classeniveau create(Classeniveau object) {
       return repo.save(object);
   }


    public List<Classeniveau> read() {
       return repo.findAll();
    }

    public Optional<Classeniveau> readById(int id) {
       return repo.findById(id);
    }

    public Classeniveau update(int id, Classeniveau object) {
       try {

           Optional<Classeniveau> optional = repo.findById(id);
           if (optional.isPresent()) {
               Classeniveau existing = optional.get();
               existing = (Classeniveau) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

