 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Classe;
 import com.spring.repository.ClasseRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class ClasseService {
    private final ClasseRepository repo;

    @Autowired
    public ClasseService(ClasseRepository rep) {
        this.repo = rep;
    }

    public Classe create(Classe object) {
       return repo.save(object);
   }


    public List<Classe> read() {
       return repo.findAll();
    }

    public Optional<Classe> readById(int id) {
       return repo.findById(id);
    }

    public Optional<Classe> readById(Long id) {
      Integer classe = Integer.parseInt(id.toString());
      return readById(classe);
    }

    public Classe update(int id, Classe object) {
       try {

           Optional<Classe> optional = repo.findById(id);
           if (optional.isPresent()) {
               Classe existing = optional.get();
               existing = (Classe) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }

    public List<Classe> getIdBetween(int startClasse, int endClasse) {
      return repo.findByIdBetween(startClasse, endClasse);
   }

   public Classe getByNom(String nom) {
      return repo.findByClasse(nom);
   }

}

