 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Commentaires;
 import com.spring.repository.CommentairesRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class CommentairesService {
    private final CommentairesRepository repo;

    public List<Commentaires> getCommentsByProgramme(Integer programmeId) {
        List<Commentaires> comments = repo.findByProgrammescolaireid(programmeId);
        comments.forEach(comment -> {
            if (comment.getReplies() != null) {
            }
        });
    
        return comments;
    }
    

  public Commentaires addComment(Commentaires commentaire) {
      return repo.save(commentaire);
  }

    @Autowired
    public CommentairesService(CommentairesRepository rep) {
        this.repo = rep;
    }

    public Commentaires create(Commentaires object) {
       return repo.save(object);
   }


    public List<Commentaires> read() {
       return repo.findAll();
    }

    public Optional<Commentaires> readById(int id) {
       return repo.findById(id);
    }

    public Commentaires update(int id, Commentaires object) {
       try {

           Optional<Commentaires> optional = repo.findById(id);
           if (optional.isPresent()) {
               Commentaires existing = optional.get();
               existing = (Commentaires) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

