 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Critereprof;
 import com.spring.repository.CritereprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class CritereprofService {
    private final CritereprofRepository repo;

    public List<Critereprof> getCritere(Integer idprof) {
      return repo.findByIdprof(idprof);
   }

    @Autowired
    public CritereprofService(CritereprofRepository rep) {
        this.repo = rep;
    }

    public Critereprof create(Critereprof object) {
       return repo.save(object);
   }


    public List<Critereprof> read() {
       return repo.findAll();
    }

    public Optional<Critereprof> readById(int id) {
       return repo.findById(id);
    }

    public Critereprof update(int id, Critereprof object) {
       try {

           Optional<Critereprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               Critereprof existing = optional.get();
               existing = (Critereprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

