 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Demandeajoutprof;
 import com.spring.repository.DemandeajoutprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class DemandeajoutprofService {
    private final DemandeajoutprofRepository repo;

    @Autowired
    public DemandeajoutprofService(DemandeajoutprofRepository rep) {
        this.repo = rep;
    }

    public Demandeajoutprof create(Demandeajoutprof object) {
       return repo.save(object);
   }


    public List<Demandeajoutprof> read() {
       return repo.findAll();
    }

    public Optional<Demandeajoutprof> readById(int id) {
       return repo.findById(id);
    }

    public Demandeajoutprof update(int id, Demandeajoutprof object) {
       try {

           Optional<Demandeajoutprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               Demandeajoutprof existing = optional.get();
               existing = (Demandeajoutprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

