 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Demandeprof;
 import com.spring.repository.DemandeprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class DemandeprofService {
    private final DemandeprofRepository repo;

   

    @Autowired
    public DemandeprofService(DemandeprofRepository rep) {
        this.repo = rep;
    }

    public Demandeprof create(Demandeprof object) {
       return repo.save(object);
   }


    public List<Demandeprof> read() {
       return repo.findAll();
    }

    public Optional<Demandeprof> readById(int id) {
       return repo.findById(id);
    }

    public Demandeprof update(int id, Demandeprof object) {
       try {

           Optional<Demandeprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               Demandeprof existing = optional.get();
               existing = (Demandeprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

