 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;

import com.spring.model.Classe;
import com.spring.model.Ecoleclasse;
 import com.spring.repository.EcoleclasseRepository;
 import java.util.List;
 import java.util.ArrayList;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class EcoleclasseService {
    private final EcoleclasseRepository repo;

    @Autowired
    private ClasseService serviceclasse;

    public List<Ecoleclasse> getEcoleclasse(int idecole) {
      return repo.findByIdEcole(idecole);
   }

    @Autowired
    public EcoleclasseService(EcoleclasseRepository rep) {
        this.repo = rep;
    }

    public Ecoleclasse create(Ecoleclasse object) {
       return repo.save(object);
   }


    public List<Ecoleclasse> read() {
       return repo.findAll();
    }

    public Optional<Ecoleclasse> readById(int id) {
       return repo.findById(id);
    }

    public Ecoleclasse update(int id, Ecoleclasse object) {
       try {

           Optional<Ecoleclasse> optional = repo.findById(id);
           if (optional.isPresent()) {
               Ecoleclasse existing = optional.get();
               existing = (Ecoleclasse) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }

    public List<Classe> getClasseByEcole(int idEcole) {
      
      List<Ecoleclasse> liste_classe_id = repo.findByIdEcole(idEcole);
      
      for (Ecoleclasse ecoleclasse : liste_classe_id) {
         System.out.println(ecoleclasse.getIdclasse());
      }
      List<Classe> liste_classe = new ArrayList();
      for (Ecoleclasse ecoleclasse : liste_classe_id) {
         Classe classe = serviceclasse.readById(ecoleclasse.getIdclasse()).get();
         liste_classe.add(classe);
      }
      return liste_classe;
    }
}

