 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Edtclasse;
 import com.spring.repository.EdtclasseRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class EdtclasseService {
    private final EdtclasseRepository repo;

    @Autowired
    public EdtclasseService(EdtclasseRepository rep) {
        this.repo = rep;
    }

    public Edtclasse create(Edtclasse object) {
       return repo.save(object);
   }


    public List<Edtclasse> read() {
       return repo.findAll();
    }

    public Optional<Edtclasse> readById(int id) {
       return repo.findById(id);
    }

    public Edtclasse update(int id, Edtclasse object) {
       try {

           Optional<Edtclasse> optional = repo.findById(id);
           if (optional.isPresent()) {
               Edtclasse existing = optional.get();
               existing = (Edtclasse) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

