 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Eleveecole;
 import com.spring.repository.EleveecoleRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class EleveecoleService {
    private final EleveecoleRepository repo;

    @Autowired
    public EleveecoleService(EleveecoleRepository rep) {
        this.repo = rep;
    }

    public Eleveecole create(Eleveecole object) {
       return repo.save(object);
   }


    public List<Eleveecole> read() {
       return repo.findAll();
    }

    public Optional<Eleveecole> readById(int id) {
       return repo.findById(id);
    }

    public Eleveecole update(int id, Eleveecole object) {
       try {

           Optional<Eleveecole> optional = repo.findById(id);
           if (optional.isPresent()) {
               Eleveecole existing = optional.get();
               existing = (Eleveecole) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

