 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Etudiant;
 import com.spring.repository.EtudiantRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class EtudiantService {
    private final EtudiantRepository repo;

    @Autowired
    public EtudiantService(EtudiantRepository rep) {
        this.repo = rep;
    }

    public Etudiant create(Etudiant object) {
       return repo.save(object);
   }


    public List<Etudiant> read() {
       return repo.findAll();
    }

    public Optional<Etudiant> readById(int id) {
       return repo.findById(id);
    }

    public Etudiant update(int id, Etudiant object) {
       try {

           Optional<Etudiant> optional = repo.findById(id);
           if (optional.isPresent()) {
               Etudiant existing = optional.get();
               existing = (Etudiant) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

