 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Etudiantecole;
 import com.spring.repository.EtudiantecoleRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class EtudiantecoleService {
    private final EtudiantecoleRepository repo;

    public Integer getSum(int idecoleclasse,int idanne) {
      return repo.getNbrEtudiant(idecoleclasse, idanne);
   }

    public List<Etudiantecole> getAnneeScolaireEtudiant(int idetudiant) {
      return repo.findByIdetudiant(idetudiant);
   }

    @Autowired
    public EtudiantecoleService(EtudiantecoleRepository rep) {
        this.repo = rep;
    }

    public List<Etudiantecole> getEtudiant(int idecoleclasse,int idanne) {
      return repo.findByIdecoleclasse(idecoleclasse,idanne);
   }

    public Etudiantecole create(Etudiantecole object) {
       return repo.save(object);
   }


    public List<Etudiantecole> read() {
       return repo.findAll();
    }

    public Optional<Etudiantecole> readById(int id) {
       return repo.findById(id);
    }

    public Etudiantecole update(int id, Etudiantecole object) {
       try {

           Optional<Etudiantecole> optional = repo.findById(id);
           if (optional.isPresent()) {
               Etudiantecole existing = optional.get();
               existing = (Etudiantecole) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

