 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Fraisdescolarite;
 import com.spring.repository.FraisdescolariteRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class FraisdescolariteService {
    private final FraisdescolariteRepository repo;

    public List<Fraisdescolarite> getFrais(int idecoleclasse) {
      return repo.frais(idecoleclasse);
   }

    public List<Fraisdescolarite> frais(int idecole,int idecoleclasse) {
      return repo.figetFrais(idecole,idecoleclasse);
   }

    @Autowired
    public FraisdescolariteService(FraisdescolariteRepository rep) {
        this.repo = rep;
    }

    public Fraisdescolarite create(Fraisdescolarite object) {
       return repo.save(object);
   }


    public List<Fraisdescolarite> read() {
       return repo.findAll();
    }

    public Optional<Fraisdescolarite> readById(int id) {
       return repo.findById(id);
    }

    public Fraisdescolarite update(int id, Fraisdescolarite object) {
       try {

           Optional<Fraisdescolarite> optional = repo.findById(id);
           if (optional.isPresent()) {
               Fraisdescolarite existing = optional.get();
               existing = (Fraisdescolarite) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

