 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Horaireprof;
 import com.spring.repository.HoraireprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class HoraireprofService {
    private final HoraireprofRepository repo;

    public List<Horaireprof> getHoraireByIdprof(Integer idprof) {
      return repo.findByProfid(idprof);
   }

    @Autowired
    public HoraireprofService(HoraireprofRepository rep) {
        this.repo = rep;
    }

    public Horaireprof create(Horaireprof object) {
       return repo.save(object);
   }


    public List<Horaireprof> read() {
       return repo.findAll();
    }

    public Optional<Horaireprof> readById(int id) {
       return repo.findById(id);
    }

    public Horaireprof update(int id, Horaireprof object) {
       try {

           Optional<Horaireprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               Horaireprof existing = optional.get();
               existing = (Horaireprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

