 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Jours;
 import com.spring.repository.JoursRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class JoursService {
    private final JoursRepository repo;

    @Autowired
    public JoursService(JoursRepository rep) {
        this.repo = rep;
    }

    public Jours create(Jours object) {
       return repo.save(object);
   }


    public List<Jours> read() {
       return repo.findAll();
    }

    public Optional<Jours> readById(int id) {
       return repo.findById(id);
    }

    public Jours update(int id, Jours object) {
       try {

           Optional<Jours> optional = repo.findById(id);
           if (optional.isPresent()) {
               Jours existing = optional.get();
               existing = (Jours) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

