 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.spring.model.Anneescolaire;
import com.spring.model.Matiereclasse;
import com.spring.model.Professeur;
import com.spring.repository.AnneescolaireRepository;
import com.spring.repository.MatiereclasseRepository;
import com.spring.repository.ProfesseurRepository;

import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class MatiereclasseService {
    private final MatiereclasseRepository repo;
    private final ProfesseurRepository repoProf;
    
    @Transactional
    public void insertMatiere(int ecoleclasse_id,String academy,String adresse,String classe) {
      repo.insertHoraireProf(academy,adresse,classe);
      repo.insertMatiereFromCsv();
      repo.insertMatiereclasse(ecoleclasse_id);
      repo.insertEdtClasse(ecoleclasse_id);
   }

    @Autowired
    public MatiereclasseService(MatiereclasseRepository rep,ProfesseurRepository p) {
        this.repo = rep;
        this.repoProf = p;
    }

    public Matiereclasse create(Matiereclasse object) {
       return repo.save(object);
   }


    public List<Matiereclasse> read() {
       return repo.findAll();
    }

    public Optional<Matiereclasse> readById(int id) {
       return repo.findById(id);
    }

    public Matiereclasse update(int id, Matiereclasse object) {
       try {

           Optional<Matiereclasse> optional = repo.findById(id);
           if (optional.isPresent()) {
               Matiereclasse existing = optional.get();
               existing = (Matiereclasse) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

