 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Matiere;
 import com.spring.repository.MatiereRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class MatiereService {
    private final MatiereRepository repo;

    @Autowired
    public MatiereService(MatiereRepository rep) {
        this.repo = rep;
    }

    public Matiere create(Matiere object) {
       return repo.save(object);
   }


    public List<Matiere> read() {
       return repo.findAll();
    }

    public Optional<Matiere> readById(int id) {
       return repo.findById(id);
    }

    public Matiere update(int id, Matiere object) {
       try {

           Optional<Matiere> optional = repo.findById(id);
           if (optional.isPresent()) {
               Matiere existing = optional.get();
               existing = (Matiere) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

