 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Media;
 import com.spring.repository.MediaRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class MediaService {
    private final MediaRepository repo;

    public List<Media> getMedia(int idecoleclasse,int idanneescolaire) {
      return repo.findMedia(idecoleclasse,idanneescolaire);
   }

    @Autowired
    public MediaService(MediaRepository rep) {
        this.repo = rep;
    }

    public Media create(Media object) {
       return repo.save(object);
   }


    public List<Media> read() {
       return repo.findAll();
    }

    public Optional<Media> readById(int id) {
       return repo.findById(id);
    }

    public Media update(int id, Media object) {
       try {

           Optional<Media> optional = repo.findById(id);
           if (optional.isPresent()) {
               Media existing = optional.get();
               existing = (Media) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

