 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Niveau;
 import com.spring.repository.NiveauRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class NiveauService {
    private final NiveauRepository repo;

    @Autowired
    public NiveauService(NiveauRepository rep) {
        this.repo = rep;
    }

    public Niveau create(Niveau object) {
       return repo.save(object);
   }


    public List<Niveau> read() {
       return repo.findAll();
    }

    public Optional<Niveau> readById(int id) {
       return repo.findById(id);
    }

    public Niveau update(int id, Niveau object) {
       try {

           Optional<Niveau> optional = repo.findById(id);
           if (optional.isPresent()) {
               Niveau existing = optional.get();
               existing = (Niveau) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

