 package com.spring.service;

import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import org.springframework.transaction.annotation.Transactional;

import com.spring.model.Csvmatiereclasse;
import com.spring.model.ImportError;
import com.spring.model.ImportResult;
import com.spring.model.Noteetudiantecole;
import com.spring.repository.NoteetudiantecoleRepository;

import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class NoteetudiantecoleService {
    private final NoteetudiantecoleRepository repo;

    @Transactional
    public void insertNotes(int idtrimestre,int idmatiereclasse,int idannee) {
      repo.insertNote(idtrimestre,idmatiereclasse,idannee);
      
   }

   public List<Noteetudiantecole> getNoteTrim(int idtrimestre,int idmatiereclasse) {
      return repo.findByIdtrimestre(idtrimestre,idmatiereclasse);
   }

    @Autowired
    public NoteetudiantecoleService(NoteetudiantecoleRepository rep) {
        this.repo = rep;
    }

    public Noteetudiantecole create(Noteetudiantecole object) {
       return repo.save(object);
   }


    public List<Noteetudiantecole> read() {
       return repo.findAll();
    }

    public Optional<Noteetudiantecole> readById(int id) {
       return repo.findById(id);
    }

    public Noteetudiantecole update(int id, Noteetudiantecole object) {
       try {

           Optional<Noteetudiantecole> optional = repo.findById(id);
           if (optional.isPresent()) {
               Noteetudiantecole existing = optional.get();
               existing = (Noteetudiantecole) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

