 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Offreecole;
 import com.spring.repository.OffreecoleRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class OffreecoleService {
    private final OffreecoleRepository repo;

    public List<Offreecole> getOffreByIdEcole(int idecole) {   
      return repo.findByEcoleId(idecole);
  }

    @Autowired
    public OffreecoleService(OffreecoleRepository rep) {
        this.repo = rep;
    }

    public Offreecole create(Offreecole object) {
       return repo.save(object);
   }


    public List<Offreecole> read() {
       return repo.findAll();
    }

    public Optional<Offreecole> readById(int id) {
       return repo.findById(id);
    }

    public Offreecole update(int id, Offreecole object) {
       try {

           Optional<Offreecole> optional = repo.findById(id);
           if (optional.isPresent()) {
               Offreecole existing = optional.get();
               existing = (Offreecole) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

