 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Parentetudiant;
 import com.spring.repository.ParentetudiantRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class ParentetudiantService {
    private final ParentetudiantRepository repo;

    @Autowired
    public ParentetudiantService(ParentetudiantRepository rep) {
        this.repo = rep;
    }

    public Parentetudiant create(Parentetudiant object) {
       return repo.save(object);
   }


    public List<Parentetudiant> read() {
       return repo.findAll();
    }

    public Optional<Parentetudiant> readById(int id) {
       return repo.findById(id);
    }

    public Parentetudiant update(int id, Parentetudiant object) {
       try {

           Optional<Parentetudiant> optional = repo.findById(id);
           if (optional.isPresent()) {
               Parentetudiant existing = optional.get();
               existing = (Parentetudiant) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

