 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Professeur;
 import com.spring.repository.ProfesseurRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class ProfesseurService {
    private final ProfesseurRepository repo;

    public Professeur findByMatricule(String matricule) {
     // System.out.println("select * from professeur where matricule = "+matricule+"\n");
      return repo.findByMatricule(matricule);
  }

    @Autowired
    public ProfesseurService(ProfesseurRepository rep) {
        this.repo = rep;
    }

    public Professeur create(Professeur object) {
       return repo.save(object);
   }

   public Professeur getProfesseurId(int userId){
      return repo.findByUserId(userId);
   }


    public List<Professeur> read() {
       return repo.findAll();
    }

    public Optional<Professeur> readById(int id) {
       return repo.findById(id);
    }

    public Professeur update(int id, Professeur object) {
       try {

           Optional<Professeur> optional = repo.findById(id);
           if (optional.isPresent()) {
               Professeur existing = optional.get();
               existing = (Professeur) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

