 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Profil;
 import com.spring.repository.ProfilRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class ProfilService {
    private final ProfilRepository repo;

    @Autowired
    public ProfilService(ProfilRepository rep) {
        this.repo = rep;
    }

    public Profil create(Profil object) {
       return repo.save(object);
   }


    public List<Profil> read() {
       return repo.findAll();
    }

    public Optional<Profil> readById(int id) {
       return repo.findById(id);
    }

    public Profil update(int id, Profil object) {
       try {

           Optional<Profil> optional = repo.findById(id);
           if (optional.isPresent()) {
               Profil existing = optional.get();
               existing = (Profil) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

