 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Reponseoffre;
 import com.spring.repository.ReponseoffreRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class ReponseoffreService {
    private final ReponseoffreRepository repo;

    @Autowired
    public ReponseoffreService(ReponseoffreRepository rep) {
        this.repo = rep;
    }

    public Reponseoffre create(Reponseoffre object) {
       return repo.save(object);
   }


    public List<Reponseoffre> read() {
       return repo.findAll();
    }

    public Optional<Reponseoffre> readById(int id) {
       return repo.findById(id);
    }

    public Reponseoffre update(int id, Reponseoffre object) {
       try {

           Optional<Reponseoffre> optional = repo.findById(id);
           if (optional.isPresent()) {
               Reponseoffre existing = optional.get();
               existing = (Reponseoffre) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

