 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Retardeleve;
 import com.spring.repository.RetardeleveRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class RetardeleveService {
    private final RetardeleveRepository repo;

    public List<Retardeleve> getRetard(int idetudiant) {
      return repo.getRetardEleve(idetudiant);
   }

    @Autowired
    public RetardeleveService(RetardeleveRepository rep) {
        this.repo = rep;
    }

    public Retardeleve create(Retardeleve object) {
       return repo.save(object);
   }


    public List<Retardeleve> read() {
       return repo.findAll();
    }

    public Optional<Retardeleve> readById(int id) {
       return repo.findById(id);
    }

    public Retardeleve update(int id, Retardeleve object) {
       try {

           Optional<Retardeleve> optional = repo.findById(id);
           if (optional.isPresent()) {
               Retardeleve existing = optional.get();
               existing = (Retardeleve) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

