 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Semestre;
 import com.spring.repository.SemestreRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class SemestreService {
    private final SemestreRepository repo;

    @Autowired
    public SemestreService(SemestreRepository rep) {
        this.repo = rep;
    }

    public Semestre create(Semestre object) {
       return repo.save(object);
   }


    public List<Semestre> read() {
       return repo.findAll();
    }

    public Optional<Semestre> readById(Long id) {
       return repo.findById(id);
    }

    public Semestre update(Long id, Semestre object) {
       try {

           Optional<Semestre> optional = repo.findById(id);
           if (optional.isPresent()) {
               Semestre existing = optional.get();
               existing = (Semestre) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(Long id) {
       repo.deleteById(id);
    }



}

