 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Trimestre;
 import com.spring.repository.TrimestreRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class TrimestreService {
    private final TrimestreRepository repo;

    public List<Trimestre> getTrimestre(int idecole,int annee) {
      return repo.findByIdecole(idecole,annee);
   }

    @Autowired
    public TrimestreService(TrimestreRepository rep) {
        this.repo = rep;
    }

    public Trimestre create(Trimestre object) {
       return repo.save(object);
   }


    public List<Trimestre> read() {
       return repo.findAll();
    }

    public Optional<Trimestre> readById(int id) {
       return repo.findById(id);
    }

    public Trimestre update(int id, Trimestre object) {
       try {

           Optional<Trimestre> optional = repo.findById(id);
           if (optional.isPresent()) {
               Trimestre existing = optional.get();
               existing = (Trimestre) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

