 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_academyannee;
 import com.spring.repository.V_academyanneeRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_academyanneeService {
    private final V_academyanneeRepository repo;

    public List<V_academyannee> findByProfid(int profid) {
      return repo.findByProfid(profid);
   }

    @Autowired
    public V_academyanneeService(V_academyanneeRepository rep) {
        this.repo = rep;
    }

    public V_academyannee create(V_academyannee object) {
       return repo.save(object);
   }


    public List<V_academyannee> read() {
       return repo.findAll();
    }

    public Optional<V_academyannee> readById(int id) {
       return repo.findById(id);
    }

    public V_academyannee update(int id, V_academyannee object) {
       try {

           Optional<V_academyannee> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_academyannee existing = optional.get();
               existing = (V_academyannee) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

