 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_classeinecole;
 import com.spring.repository.V_classeinecoleRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_classeinecoleService {
    private final V_classeinecoleRepository repo;

    public List<V_classeinecole> getClasseEcole(Integer idecole) {
      return repo.findByIdecole(idecole);
   }

    @Autowired
    public V_classeinecoleService(V_classeinecoleRepository rep) {
        this.repo = rep;
    }

    public V_classeinecole create(V_classeinecole object) {
       return repo.save(object);
   }


    public List<V_classeinecole> read() {
       return repo.findAll();
    }

    public Optional<V_classeinecole> readById(int id) {
       return repo.findById(id);
    }

    public V_classeinecole update(int id, V_classeinecole object) {
       try {

           Optional<V_classeinecole> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_classeinecole existing = optional.get();
               existing = (V_classeinecole) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

