 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;

import com.spring.model.Demandeprof;
import com.spring.model.V_demandeprof;
 import com.spring.repository.V_demandeprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_demandeprofService {
    private final V_demandeprofRepository repo;

     public List<V_demandeprof> getDemandeByEcoleid(Integer ecoleid) {
      List<V_demandeprof> liste = repo.findByEcoleidStatut(ecoleid,0);
      return liste;
   }

    public List<V_demandeprof> findDemandeByProf(int profId){
      List<V_demandeprof> liste = repo.findByProfid(profId,0);
      return liste;
    }

    public List<V_demandeprof> findDemandeNull(int profId){
      List<V_demandeprof> liste = repo.findDemandeNull(profId);
      return liste;
    }

    @Autowired
    public V_demandeprofService(V_demandeprofRepository rep) {
        this.repo = rep;
    }

    public V_demandeprof create(V_demandeprof object) {
       return repo.save(object);
   }


    public List<V_demandeprof> read() {
       return repo.findAll();
    }

    public Optional<V_demandeprof> readById(int id) {
       return repo.findById(id);
    }

    public V_demandeprof update(int id, V_demandeprof object) {
       try {

           Optional<V_demandeprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_demandeprof existing = optional.get();
               existing = (V_demandeprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

