 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_ecoleclasse;
 import com.spring.repository.V_ecoleclasseRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_ecoleclasseService {
    private final V_ecoleclasseRepository repo;

    public List<V_ecoleclasse> getByEcoleclasseid(int ecoleclasseid) {
      return repo.findByEcoleclasseid(ecoleclasseid);
   }


    @Autowired
    public V_ecoleclasseService(V_ecoleclasseRepository rep) {
        this.repo = rep;
    }

    public V_ecoleclasse create(V_ecoleclasse object) {
       return repo.save(object);
   }


    public List<V_ecoleclasse> read() {
       return repo.findAll();
    }

    public Optional<V_ecoleclasse> readById(int id) {
       return repo.findById(id);
    }

    public V_ecoleclasse update(int id, V_ecoleclasse object) {
       try {

           Optional<V_ecoleclasse> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_ecoleclasse existing = optional.get();
               existing = (V_ecoleclasse) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }

    public List<V_ecoleclasse> findByIduser(int userid) {
      return repo.findByIduser(userid);
  }



}

