 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_ecolageparannee;
 import com.spring.repository.V_ecolageparanneeRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_ecolageparanneeService {
    private final V_ecolageparanneeRepository repo;

    public List<V_ecolageparannee> getV_ecolage() {
      return repo.getV_ecolageparannees();
   }

    @Autowired
    public V_ecolageparanneeService(V_ecolageparanneeRepository rep) {
        this.repo = rep;
    }

    public V_ecolageparannee create(V_ecolageparannee object) {
       return repo.save(object);
   }


    public List<V_ecolageparannee> read() {
       return repo.findAll();
    }

    public Optional<V_ecolageparannee> readById(int id) {
       return repo.findById(id);
    }

    public V_ecolageparannee update(int id, V_ecolageparannee object) {
       try {

           Optional<V_ecolageparannee> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_ecolageparannee existing = optional.get();
               existing = (V_ecolageparannee) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

