 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_edtclasse;
 import com.spring.repository.V_edtclasseRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_edtclasseService {
    private final V_edtclasseRepository repo;

    public List<V_edtclasse> edtClasse(Integer classeId,Integer idannne) {
      return repo.findEdtClasseAnne(classeId,idannne);
   }

    @Autowired
    public V_edtclasseService(V_edtclasseRepository rep) {
        this.repo = rep;
    }

    public V_edtclasse create(V_edtclasse object) {
       return repo.save(object);
   }


    public List<V_edtclasse> read() {
       return repo.findAll();
    }

    public Optional<V_edtclasse> readById(int id) {
       return repo.findById(id);
    }

    public V_edtclasse update(int id, V_edtclasse object) {
       try {

           Optional<V_edtclasse> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_edtclasse existing = optional.get();
               existing = (V_edtclasse) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

