 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_fraisscolarite;
 import com.spring.repository.V_fraisscolariteRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_fraisscolariteService {
    private final V_fraisscolariteRepository repo;

    public List<V_fraisscolarite> getEcolage(int idecole) {
      return repo.findByIdecole(idecole);
   }

    @Autowired
    public V_fraisscolariteService(V_fraisscolariteRepository rep) {
        this.repo = rep;
    }

    public V_fraisscolarite create(V_fraisscolarite object) {
       return repo.save(object);
   }


    public List<V_fraisscolarite> read() {
       return repo.findAll();
    }

    public Optional<V_fraisscolarite> readById(int id) {
       return repo.findById(id);
    }

    public V_fraisscolarite update(int id, V_fraisscolarite object) {
       try {

           Optional<V_fraisscolarite> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_fraisscolarite existing = optional.get();
               existing = (V_fraisscolarite) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

