 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_horaireprof;
 import com.spring.repository.V_horaireprofRepository;

import java.sql.Time;
import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_horaireprofService {
    private final V_horaireprofRepository repo;

    public List<V_horaireprof> getHoraireProfByid(Integer idprof) {
      return repo.findByIdprof(idprof);
   }

    public List<V_horaireprof> getHoraireProf(String jour,Time debut,Time fin,int idprof,int idanne) {
      return repo.getHoraireProf(jour,debut,fin,idprof,idanne);
   }

    @Autowired
    public V_horaireprofService(V_horaireprofRepository rep) {
        this.repo = rep;
    }

    public V_horaireprof create(V_horaireprof object) {
       return repo.save(object);
   }


    public List<V_horaireprof> read() {
       return repo.findAll();
    }

    public Optional<V_horaireprof> readById(int id) {
       return repo.findById(id);
    }

    public V_horaireprof update(int id, V_horaireprof object) {
       try {

           Optional<V_horaireprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_horaireprof existing = optional.get();
               existing = (V_horaireprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

