 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_infoetudiant;
 import com.spring.repository.V_infoetudiantRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_infoetudiantService {
    private final V_infoetudiantRepository repo;

    public List<V_infoetudiant> getInfoEtudiant(int idetudiant) {
      return repo.findByIdetudiant(idetudiant);
   }

    @Autowired
    public V_infoetudiantService(V_infoetudiantRepository rep) {
        this.repo = rep;
    }

    public V_infoetudiant create(V_infoetudiant object) {
       return repo.save(object);
   }


    public List<V_infoetudiant> read() {
       return repo.findAll();
    }

    public Optional<V_infoetudiant> readById(int id) {
       return repo.findById(id);
    }

    public V_infoetudiant update(int id, V_infoetudiant object) {
       try {

           Optional<V_infoetudiant> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_infoetudiant existing = optional.get();
               existing = (V_infoetudiant) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

