 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_matiereclasse;
 import com.spring.repository.V_matiereclasseRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_matiereclasseService {
    private final V_matiereclasseRepository repo;

    
    public List<V_matiereclasse> getMC(int ecoleclasseid,int idannee) {
      return repo.getMatiereClasse(ecoleclasseid,idannee);
   }

    public List<V_matiereclasse> findMatiereclasse(int idprof,int idannee) {
      return repo.findMatiereclasse(idprof,idannee);
   }

    @Autowired
    public V_matiereclasseService(V_matiereclasseRepository rep) {
        this.repo = rep;
    }

    public V_matiereclasse create(V_matiereclasse object) {
       return repo.save(object);
   }


    public List<V_matiereclasse> read() {
       return repo.findAll();
    }

    public Optional<V_matiereclasse> readById(int id) {
       return repo.findById(id);
    }

    public V_matiereclasse update(int id, V_matiereclasse object) {
       try {

           Optional<V_matiereclasse> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_matiereclasse existing = optional.get();
               existing = (V_matiereclasse) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

