 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_matiereandprof;
 import com.spring.repository.V_matiereandprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_matiereandprofService {
    private final V_matiereandprofRepository repo;

    @Autowired
    public V_matiereandprofService(V_matiereandprofRepository rep) {
        this.repo = rep;
    }

    public V_matiereandprof create(V_matiereandprof object) {
       return repo.save(object);
   }


    public List<V_matiereandprof> read() {
       return repo.findAll();
    }

    public List<V_matiereandprof> readByEcoleclasse_id(int ecoleclasse_id,int idannee) {
      return repo.findMatiereProfClasseAnnee(ecoleclasse_id,idannee);
   }


    public Optional<V_matiereandprof> readById(int id) {
       return repo.findById(id);
    }

    public V_matiereandprof update(int id, V_matiereandprof object) {
       try {

           Optional<V_matiereandprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_matiereandprof existing = optional.get();
               existing = (V_matiereandprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

