 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_month;
 import com.spring.repository.V_monthRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_monthService {
    private final V_monthRepository repo;

    public List<V_month> getMois(int id) {
      return repo.findVMonth(id);
   }

    @Autowired
    public V_monthService(V_monthRepository rep) {
        this.repo = rep;
    }

    public V_month create(V_month object) {
       return repo.save(object);
   }


    public List<V_month> read() {
       return repo.findAll();
    }

    public Optional<V_month> readById(int id) {
       return repo.findById(id);
    }

    public V_month update(int id, V_month object) {
       try {

           Optional<V_month> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_month existing = optional.get();
               existing = (V_month) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

