 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_moyenne;
 import com.spring.repository.V_moyenneRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_moyenneService {
    private final V_moyenneRepository repo;

    public List<V_moyenne> getMoyennes(int idanneescolaire) {
      return repo.findByIdanneescolaire(idanneescolaire);
   }

    @Autowired
    public V_moyenneService(V_moyenneRepository rep) {
        this.repo = rep;
    }

    public V_moyenne create(V_moyenne object) {
       return repo.save(object);
   }


    public List<V_moyenne> read() {
       return repo.findAll();
    }

    public Optional<V_moyenne> readById(int id) {
       return repo.findById(id);
    }

    public V_moyenne update(int id, V_moyenne object) {
       try {

           Optional<V_moyenne> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_moyenne existing = optional.get();
               existing = (V_moyenne) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

