 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_parentetudiant;
 import com.spring.repository.V_parentetudiantRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_parentetudiantService {
    private final V_parentetudiantRepository repo;

    public List<V_parentetudiant> getEnfant(int idparent) {
      return repo.findByIdparent(idparent);
   }

    @Autowired
    public V_parentetudiantService(V_parentetudiantRepository rep) {
        this.repo = rep;
    }

    public V_parentetudiant create(V_parentetudiant object) {
       return repo.save(object);
   }


    public List<V_parentetudiant> read() {
       return repo.findAll();
    }

    public Optional<V_parentetudiant> readById(int id) {
       return repo.findById(id);
    }

    public V_parentetudiant update(int id, V_parentetudiant object) {
       try {

           Optional<V_parentetudiant> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_parentetudiant existing = optional.get();
               existing = (V_parentetudiant) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

