 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;

import com.spring.model.Demandeajoutprof;
import com.spring.model.V_infoprof;
import com.spring.model.V_profnotinacademy;
import com.spring.repository.DemandeajoutprofRepository;
import com.spring.repository.V_profnotinacademyRepository;
 import java.util.List;
 import java.util.Optional;
 import java.util.stream.Collectors;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_profnotinacademyService {
    private final V_profnotinacademyRepository repo;

   private final DemandeajoutprofRepository demandeajoutprofRepository;


    public List<V_profnotinacademy> readAcademyProf(int academyid) {
      List<Demandeajoutprof> listAc = demandeajoutprofRepository.findByIdacademy(academyid);
      List<V_profnotinacademy> listV_info = this.read();

      for (V_profnotinacademy v_infoprof2 : listV_info) {
         List<Demandeajoutprof> academProf = listAc.stream().filter(v_infoprof -> v_infoprof.getIdprof() == v_infoprof2.getIdprof()).collect(Collectors.toList());

         //System.out.print("statut  "+academProf.size());
         
         if(academProf.size() > 0){
            v_infoprof2.setStatus(1);
         }else{
            v_infoprof2.setStatus(0);
         }
      }

      
      return listV_info;
   }

    @Autowired
    public V_profnotinacademyService(V_profnotinacademyRepository rep,DemandeajoutprofRepository repoB) {
        this.repo = rep;
         this.demandeajoutprofRepository = repoB;
    }

    public V_profnotinacademy create(V_profnotinacademy object) {
       return repo.save(object);
   }


    public List<V_profnotinacademy> read() {
       return repo.findAll();
    }

    public Optional<V_profnotinacademy> readById(int id) {
       return repo.findById(id);
    }

    public V_profnotinacademy update(int id, V_profnotinacademy object) {
       try {

           Optional<V_profnotinacademy> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_profnotinacademy existing = optional.get();
               existing = (V_profnotinacademy) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

