 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_profilprof;
 import com.spring.repository.V_profilprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_profilprofService {
    private final V_profilprofRepository repo;

    public List<V_profilprof> getProfilProf(int iduser) {
      return repo.findByIduser(iduser);
   }


    @Autowired
    public V_profilprofService(V_profilprofRepository rep) {
        this.repo = rep;
    }

    public V_profilprof create(V_profilprof object) {
       return repo.save(object);
   }


    public List<V_profilprof> read() {
       return repo.findAll();
    }

    public Optional<V_profilprof> readById(int id) {
       return repo.findById(id);
    }

    public V_profilprof update(int id, V_profilprof object) {
       try {

           Optional<V_profilprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_profilprof existing = optional.get();
               existing = (V_profilprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

