 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;

import com.spring.model.V_reponseoffre;
 import com.spring.repository.V_reponseoffreRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_reponseoffreService {
    private final V_reponseoffreRepository repo;

    public List<V_reponseoffre> getOffreById(int id){
      List<V_reponseoffre> liste = repo.findByProfid(id);
      return liste;
  }

    public List<V_reponseoffre> findDemandeNull(int id){
      List<V_reponseoffre> liste = repo.findOffreNull(id);
      return liste;
  }
  
    @Autowired
    public V_reponseoffreService(V_reponseoffreRepository rep) {
        this.repo = rep;
    }

    public V_reponseoffre create(V_reponseoffre object) {
       return repo.save(object);
   }


    public List<V_reponseoffre> read() {
       return repo.findAll();
    }

    public Optional<V_reponseoffre> readById(int id) {
       return repo.findById(id);
    }

    public V_reponseoffre update(int id, V_reponseoffre object) {
       try {

           Optional<V_reponseoffre> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_reponseoffre existing = optional.get();
               existing = (V_reponseoffre) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

