 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_salaireprof;
 import com.spring.repository.V_salaireprofRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_salaireprofService {
    private final V_salaireprofRepository repo;

    public List<V_salaireprof> getSalaire(int idecole) {
      return repo.findByIdecole(idecole);
   }


    @Autowired
    public V_salaireprofService(V_salaireprofRepository rep) {
        this.repo = rep;
    }

    public V_salaireprof create(V_salaireprof object) {
       return repo.save(object);
   }


    public List<V_salaireprof> read() {
       return repo.findAll();
    }

    public Optional<V_salaireprof> readById(int id) {
       return repo.findById(id);
    }

    public V_salaireprof update(int id, V_salaireprof object) {
       try {

           Optional<V_salaireprof> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_salaireprof existing = optional.get();
               existing = (V_salaireprof) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

