 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_salaireparannee;
 import com.spring.repository.V_salaireparanneeRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_salaireparanneeService {
    private final V_salaireparanneeRepository repo;

    @Autowired
    public V_salaireparanneeService(V_salaireparanneeRepository rep) {
        this.repo = rep;
    }

    public V_salaireparannee create(V_salaireparannee object) {
       return repo.save(object);
   }


    public List<V_salaireparannee> read() {
       return repo.findAll();
    }

    public Optional<V_salaireparannee> readById(int id) {
       return repo.findById(id);
    }

    public V_salaireparannee update(int id, V_salaireparannee object) {
       try {

           Optional<V_salaireparannee> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_salaireparannee existing = optional.get();
               existing = (V_salaireparannee) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

