 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.V_salaireannuel;
 import com.spring.repository.V_salaireannuelRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_salaireannuelService {
    private final V_salaireannuelRepository repo;

    @Autowired
    public V_salaireannuelService(V_salaireannuelRepository rep) {
        this.repo = rep;
    }

    public V_salaireannuel create(V_salaireannuel object) {
       return repo.save(object);
   }


    public List<V_salaireannuel> read() {
       return repo.findAll();
    }

    public Optional<V_salaireannuel> readById(int id) {
       return repo.findById(id);
    }

    public V_salaireannuel update(int id, V_salaireannuel object) {
       try {

           Optional<V_salaireannuel> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_salaireannuel existing = optional.get();
               existing = (V_salaireannuel) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

