 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;

import com.spring.model.V_totalsalairepannee;
 import com.spring.repository.V_totalsalairepanneeRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_totalsalairepanneeService {
    private final V_totalsalairepanneeRepository repo;

    public Double getSumm(int idanneescolaire) {
      return repo.getSomme(idanneescolaire);
  }


    @Autowired
    public V_totalsalairepanneeService(V_totalsalairepanneeRepository rep) {
        this.repo = rep;
    }

    public V_totalsalairepannee create(V_totalsalairepannee object) {
       return repo.save(object);
   }


    public List<V_totalsalairepannee> read() {
       return repo.findAll();
    }

    public Optional<V_totalsalairepannee> readById(int id) {
       return repo.findById(id);
    }

    public V_totalsalairepannee update(int id, V_totalsalairepannee object) {
       try {

           Optional<V_totalsalairepannee> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_totalsalairepannee existing = optional.get();
               existing = (V_totalsalairepannee) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

