 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;

import com.spring.model.V_demandeprof;
import com.spring.model.V_voirdemande;
 import com.spring.repository.V_voirdemandeRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class V_voirdemandeService {
    private final V_voirdemandeRepository repo;

    public List<V_voirdemande> findDemandeRecu(int ecoleId){
      List<V_voirdemande> liste = repo.findByEcoleId(ecoleId);
      return liste;
    }
    @Autowired
    public V_voirdemandeService(V_voirdemandeRepository rep) {
        this.repo = rep;
    }

    public V_voirdemande create(V_voirdemande object) {
       return repo.save(object);
   }


    public List<V_voirdemande> read() {
       return repo.findAll();
    }

    public Optional<V_voirdemande> readById(int id) {
       return repo.findById(id);
    }

    public V_voirdemande update(int id, V_voirdemande object) {
       try {

           Optional<V_voirdemande> optional = repo.findById(id);
           if (optional.isPresent()) {
               V_voirdemande existing = optional.get();
               existing = (V_voirdemande) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }



}

