 package com.spring.service;

 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import com.spring.model.Verifemail;
 import com.spring.repository.VerifemailRepository;
 import java.util.List;
 import java.util.Optional;

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Service
 public class VerifemailService {
    private final VerifemailRepository repo;

    @Autowired
    public VerifemailService(VerifemailRepository rep) {
        this.repo = rep;
    }

    public Verifemail create(Verifemail object) {
       return repo.save(object);
   }

   public List<Verifemail> findOne(String email1,String token1) {
      List<Verifemail> liste = repo.findOne(email1, token1);
      return liste;
   }

   public List<Verifemail> tokenEmail(String email1,String email2,String token1,String token2) {
      List<Verifemail> liste = repo.findVerifEmails(email1, token1, email2, token2);
      return liste;
   }

    public List<Verifemail> read() {
       return repo.findAll();
    }

    public Optional<Verifemail> readById(int id) {
       return repo.findById(id);
    }

    public Verifemail update(int id, Verifemail object) {
       try {

           Optional<Verifemail> optional = repo.findById(id);
           if (optional.isPresent()) {
               Verifemail existing = optional.get();
               existing = (Verifemail) com.spring.utility.Utilitaire.addValueObject(existing,object);
               return repo.save(existing);
           }
       return null;
       }catch(Exception ex){
           ex.printStackTrace();
           return null;
       }
    }

    public void delete(int id) {
       repo.deleteById(id);
    }

   
    public void deleteAll() {
      repo.deleteAll();
    }



}

