 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Absenceeleve")
 public class Absenceeleve {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idetudiantecole")
     Integer idetudiantecole;
     @Column(name = "dateabsdebut")
     Date dateabsdebut;
     @Column(name = "dateabsfin")
     Date dateabsfin;
     @Column(name = "motif")
     String motif;
     @Column(name = "dateajout")
     Date dateajout;
     @Column(name = "profilexpediteur")
     Integer profilexpediteur;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdetudiantecole(){
        return idetudiantecole;
    }


    public void setIdetudiantecole(Integer obj){
         idetudiantecole = obj;
    }


    public Date getDateabsdebut(){
        return dateabsdebut;
    }


    public void setDateabsdebut(Date obj){
         dateabsdebut = obj;
    }


    public Date getDateabsfin(){
        return dateabsfin;
    }


    public void setDateabsfin(Date obj){
         dateabsfin = obj;
    }


    public String getMotif(){
        return motif;
    }


    public void setMotif(String obj){
         motif = obj;
    }


    public Date getDateajout(){
        return dateajout;
    }


    public void setDateajout(Date obj){
         dateajout = obj;
    }


    public Integer getProfilexpediteur(){
        return profilexpediteur;
    }


    public void setProfilexpediteur(Integer obj){
         profilexpediteur = obj;
    }



}

