 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 
import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Absence")
 public class Absence {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "dateabsence")
     Date dateabsence;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "idetudiant")
     Integer idetudiant;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Date getDateabsence(){
        return dateabsence;
    }


    public void setDateabsence(Date obj){
         dateabsence = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }



}

