 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;

import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.util.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Academy")
 public class Academy {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id")
     Integer id;

     @Column(name = "nom")
     String nom;
     @Column(name = "adresse")
     String adresse;
     @Column(name = "description")
     String description;
     @Column(name = "numtel")
     String numtel;
     @Column(name = "email")
     String email;
     @Column(name = "datecreationecole")
     Date datecreationecole;
     @Column(name = "dateinscriptionecole")
     @Temporal(TemporalType.TIMESTAMP)
     Date dateinscriptionecole;
     @Column(name = "prefixe")
     String prefixe;
     @Column(name = "logo")
     String logo;
     @Column(name = "idtype")
     Integer idtype;

    @PrePersist
    protected void onCreate() {
        if (dateinscriptionecole == null) {
            dateinscriptionecole = new Date();
        }
    }


     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "academy_id")
     private List<Academyusers>  academyuserss;

     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "idecole")
     private List<Anneescolaire>  anneescolaires;

     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "idecole")
     private List<Ecoleclasse>  ecoleclasses;
     
     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getAdresse(){
        return adresse;
    }


    public void setAdresse(String obj){
         adresse = obj;
    }


    public String getDescription(){
        return description;
    }


    public void setDescription(String obj){
         description = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public Date getDatecreationecole(){
        return datecreationecole;
    }


    public void setDatecreationecole(Date obj){
         datecreationecole = obj;
    }


    public Date getDateinscriptionecole(){
        return dateinscriptionecole;
    }


    public void setDateinscriptionecole(Date obj){
         dateinscriptionecole = obj;
    }


    public String getPrefixe(){
        return prefixe;
    }


    public void setPrefixe(String obj){
         prefixe = obj;
    }


    public String getLogo(){
        return logo;
    }


    public void setLogo(String obj){
         logo = obj;
    }


    public Integer getIdtype(){
        return idtype;
    }


    public void setIdtype(Integer obj){
         idtype = obj;
    }


    public List<Academyusers> getAcademyuserss(){
        return academyuserss;
    }


    public void setAcademyuserss(List<Academyusers> obj){
         academyuserss = obj;
    }


    public List<Anneescolaire> getAnneescolaires(){
        return anneescolaires;
    }


    public void setAnneescolaires(List<Anneescolaire> obj){
         anneescolaires = obj;
    }


    public List<Ecoleclasse> getEcoleclasses(){
        return ecoleclasses;
    }


    public void setEcoleclasses(List<Ecoleclasse> obj){
         ecoleclasses = obj;
    }



}

