 package com.spring.model;

 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "academyusers")
 public class Academyusers {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id")
     Integer id;

     @Column(name = "users_id")
     Integer users;
     @Column(name = "academy_id")
     Integer academy_id;
     
    public Integer getId(){
        return id;
    }
   
    public void setId(Integer obj){
         id = obj;
    }


    public Integer getUsers(){
        return users;

    }


    public void setUsers(Integer obj){
         users = obj;
    }


    public Integer getAcademy_id(){
        return academy_id;
    }


    public void setAcademy_id(Integer obj){
         academy_id = obj;
    }



}

