 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Academyprof")
 public class Academyprof {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "academyid")
     Integer academyid;
     @Column(name = "profid")
     Integer profid;
     


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getAcademyid(){
        return academyid;
    }


    public void setAcademyid(Integer obj){
         academyid = obj;
    }


    public Integer getProfid(){
        return profid;
    }


    public void setProfid(Integer obj){
         profid = obj;
    }



}

