 package com.spring.model;

 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Anneescolaire")
 public class Anneescolaire {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idecole")
     Integer idecole;
     @Column(name = "debutanneescolaire")
     Date debutanneescolaire;
     @Column(name = "finanneescolaire")
     Date finanneescolaire;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdecole(){
        return idecole;
    }


    public void setIdecole(Integer obj){
         idecole = obj;
    }


    public Date getDebutanneescolaire(){
        return debutanneescolaire;
    }


    public void setDebutanneescolaire(Date obj){
         debutanneescolaire = obj;
    }


    public Date getFinanneescolaire(){
        return finanneescolaire;
    }


    public void setFinanneescolaire(Date obj){
         finanneescolaire = obj;
    }



}

