 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Calendrierscolaire")
 public class Calendrierscolaire {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idecole")
     Integer idecole;
     @Column(name = "motif")
     String motif;
     @Column(name = "descriptions")
     String descriptions;
     @Column(name = "datedebut")
     Date datedebut;
     @Column(name = "datefin")
     Date datefin;
     @Column(name = "statut")
     Integer statut;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdecole(){
        return idecole;
    }


    public void setIdecole(Integer obj){
         idecole = obj;
    }


    public String getMotif(){
        return motif;
    }


    public void setMotif(String obj){
         motif = obj;
    }


    public String getDescriptions(){
        return descriptions;
    }


    public void setDescriptions(String obj){
         descriptions = obj;
    }


    public Date getDatedebut(){
        return datedebut;
    }


    public void setDatedebut(Date obj){
         datedebut = obj;
    }


    public Date getDatefin(){
        return datefin;
    }


    public void setDatefin(Date obj){
         datefin = obj;
    }


    public Integer getStatut(){
        return statut;
    }


    public void setStatut(Integer obj){
         statut = obj;
    }



}

