 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;

import java.sql.Date;
import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Carnettout")
 public class Carnettout {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idecoleclasse")
     Integer idecoleclasse;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "datecreation")
     Date datecreation;
     @Column(name = "descriptions")
     String descriptions;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdecoleclasse(){
        return idecoleclasse;
    }


    public void setIdecoleclasse(Integer obj){
         idecoleclasse = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Date getDatecreation(){
        return datecreation;
    }


    public void setDatecreation(Date obj){
         datecreation = obj;
    }


    public String getDescriptions(){
        return descriptions;
    }


    public void setDescriptions(String obj){
         descriptions = obj;
    }



}

