 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Carneteleve")
 public class Carneteleve {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "datecarnet")
     Date datecarnet;
     @Column(name = "descriptions")
     String descriptions;
     @Column(name = "profilexpediteur")
     Integer profilexpediteur;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public Date getDatecarnet(){
        return datecarnet;
    }


    public void setDatecarnet(Date obj){
         datecarnet = obj;
    }


    public String getDescriptions(){
        return descriptions;
    }


    public void setDescriptions(String obj){
         descriptions = obj;
    }


    public Integer getProfilexpediteur(){
        return profilexpediteur;
    }


    public void setProfilexpediteur(Integer obj){
         profilexpediteur = obj;
    }



}

