 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Classeniveau")
 public class Classeniveau {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idniveau")
     Integer idniveau;
     @Column(name = "idclasse")
     Integer idclasse;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdniveau(){
        return idniveau;
    }


    public void setIdniveau(Integer obj){
         idniveau = obj;
    }


    public Integer getIdclasse(){
        return idclasse;
    }


    public void setIdclasse(Integer obj){
         idclasse = obj;
    }



}

