 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Classe")
 public class Classe {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "classe")
     String classe;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "idclasse")
     private List<Ecoleclasse>  ecoleclasses;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getClasse(){
        return classe;
    }


    public void setClasse(String obj){
         classe = obj;
    }


    public List<Ecoleclasse> getEcoleclasses(){
        return ecoleclasses;
    }


    public void setEcoleclasses(List<Ecoleclasse> obj){
         ecoleclasses = obj;
    }



}

