 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Critereprof")
 public class Critereprof {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idprof")
     Integer idprof;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "classe")
     String classe;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdprof(){
        return idprof;
    }


    public void setIdprof(Integer obj){
         idprof = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public String getClasse(){
        return classe;
    }


    public void setClasse(String obj){
         classe = obj;
    }



}

