 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
import jakarta.persistence.Transient;

import java.sql.Time;
import java.sql.Time;
import java.sql.Time;
import java.sql.Time;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Csvmatiereclasse")
 public class Csvmatiereclasse {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "matricule")
     String matricule;
     @Column(name = "coefficient")
     Integer coefficient;
     @Column(name = "jour")
     String jour;
     @Column(name = "heuredebut")
     Time heuredebut;
     @Column(name = "heurefin")
     Time heurefin;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
    @Transient
     Integer idprof;

     
    public Integer getIdprof() {
        return idprof;
    }


    public void setIdprof(Integer idprof) {
        this.idprof = idprof;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public String getMatricule(){
        return matricule;
    }


    public void setMatricule(String obj){
         matricule = obj;
    }


    public Integer getCoefficient(){
        return coefficient;
    }


    public void setCoefficient(Integer obj){
         coefficient = obj;
    }


    public String getJour(){
        return jour;
    }


    public void setJour(String obj){
         jour = obj;
    }


    public Time getHeuredebut(){
        return heuredebut;
    }


    public void setHeuredebut(Time obj){
         heuredebut = obj;
    }


    public Time getHeurefin(){
        return heurefin;
    }


    public void setHeurefin(Time obj){
         heurefin = obj;
    }

    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }



}

