 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Demandeajoutprof")
 public class Demandeajoutprof {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idacademy")
     Integer idacademy;
     @Column(name = "idprof")
     Integer idprof;
     @Column(name = "dateajout")
     Date dateajout;
     @Column(name = "statut")
     Integer statut;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdacademy(){
        return idacademy;
    }


    public void setIdacademy(Integer obj){
         idacademy = obj;
    }


    public Integer getIdprof(){
        return idprof;
    }


    public void setIdprof(Integer obj){
         idprof = obj;
    }


    public Date getDateajout(){
        return dateajout;
    }


    public void setDateajout(Date obj){
         dateajout = obj;
    }


    public Integer getStatut(){
        return statut;
    }


    public void setStatut(Integer obj){
         statut = obj;
    }



}

