 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Time;
import java.sql.Time;
import java.sql.Time;
import java.sql.Time;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Edtclasse")
 public class Edtclasse {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "ecoleclasse_id")
     Integer ecoleclasse_id;
     @Column(name = "matiere_id")
     Integer matiere_id;
     @Column(name = "jourid")
     Integer jourid;
     @Column(name = "heuredebut")
     Time heuredebut;
     @Column(name = "heurefin")
     Time heurefin;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     
    public Integer getIdanneescolaire() {
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer idanneescolaire) {
        this.idanneescolaire = idanneescolaire;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getEcoleclasse_id(){
        return ecoleclasse_id;
    }


    public void setEcoleclasse_id(Integer obj){
         ecoleclasse_id = obj;
    }


    public Integer getMatiere_id(){
        return matiere_id;
    }


    public void setMatiere_id(Integer obj){
         matiere_id = obj;
    }


    public Integer getJourid(){
        return jourid;
    }


    public void setJourid(Integer obj){
         jourid = obj;
    }


    public Time getHeuredebut(){
        return heuredebut;
    }


    public void setHeuredebut(Time obj){
         heuredebut = obj;
    }


    public Time getHeurefin(){
        return heurefin;
    }


    public void setHeurefin(Time obj){
         heurefin = obj;
    }



}

