 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Eleveecole")
 public class Eleveecole {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "idecole")
     Integer idecole;
     @Column(name = "prefixe")
     String prefixe;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public Integer getIdecole(){
        return idecole;
    }


    public void setIdecole(Integer obj){
         idecole = obj;
    }


    public String getPrefixe(){
        return prefixe;
    }


    public void setPrefixe(String obj){
         prefixe = obj;
    }



}

