 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Etudiant")
 public class Etudiant {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "nom")
     String nom;
     @Column(name = "prenom")
     String prenom;
     @Column(name = "datenaissance")
     Date datenaissance;
     @Column(name = "adresse")
     String adresse;
     @Column(name = "email")
     String email;
     @Column(name = "contact")
     String contact;
     @Column(name = "photo")
     String photo;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "idetudiant")
     private List<Etudiantecole>  etudiantecoles;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "idetudiant")
     private List<Parentetudiant>  parentetudiants;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getPrenom(){
        return prenom;
    }


    public void setPrenom(String obj){
         prenom = obj;
    }


    public Date getDatenaissance(){
        return datenaissance;
    }


    public void setDatenaissance(Date obj){
         datenaissance = obj;
    }


    public String getAdresse(){
        return adresse;
    }


    public void setAdresse(String obj){
         adresse = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public String getContact(){
        return contact;
    }


    public void setContact(String obj){
         contact = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }


    public List<Etudiantecole> getEtudiantecoles(){
        return etudiantecoles;
    }


    public void setEtudiantecoles(List<Etudiantecole> obj){
         etudiantecoles = obj;
    }


    public List<Parentetudiant> getParentetudiants(){
        return parentetudiants;
    }


    public void setParentetudiants(List<Parentetudiant> obj){
         parentetudiants = obj;
    }



}

