 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Ficheecolage")
 public class Ficheecolage {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "mois")
     String mois;
     @Column(name = "frais")
     Double frais;
     @Column(name = "statut")
     Integer statut;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public String getMois(){
        return mois;
    }


    public void setMois(String obj){
         mois = obj;
    }


    public Double getFrais(){
        return frais;
    }


    public void setFrais(Double obj){
         frais = obj;
    }


    public Integer getStatut(){
        return statut;
    }


    public void setStatut(Integer obj){
         statut = obj;
    }



}

