 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Time;
import java.sql.Time;
import java.sql.Time;
import java.sql.Time;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Horaireprof")
 public class Horaireprof {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "profid")
     Integer profid;
     @Column(name = "jourid")
     Integer jourid;
     @Column(name = "heuredebut")
     Time heuredebut;
     @Column(name = "heurefin")
     Time heurefin;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "academy")
     String academy;
    @Column(name = "adresse")
     String adresse;
    @Column(name = "classe")
     String classe;

     
     public String getClasse() {
        return classe;
    }


    public void setClasse(String classe) {
        this.classe = classe;
    }


    public String getAdresse() {
        return adresse;
    }


    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }



     public String getAcademy() {
        return academy;
    }


    public void setAcademy(String academy) {
        this.academy = academy;
    }



     
    public Integer getIdanneescolaire() {
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer idanneescolaire) {
        this.idanneescolaire = idanneescolaire;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getProfid(){
        return profid;
    }


    public void setProfid(Integer obj){
         profid = obj;
    }


    public Integer getJourid(){
        return jourid;
    }


    public void setJourid(Integer obj){
         jourid = obj;
    }


    public Time getHeuredebut(){
        return heuredebut;
    }


    public void setHeuredebut(Time obj){
         heuredebut = obj;
    }


    public Time getHeurefin(){
        return heurefin;
    }


    public void setHeurefin(Time obj){
         heurefin = obj;
    }



}

