 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Matiere")
 public class Matiere {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "matiere")
     String matiere;
   
    @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "matiere_id")
     private List<Matiereclasse>  matiereclasses;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public List<Matiereclasse> getMatiereclasses(){
        return matiereclasses;
    }


    public void setMatiereclasses(List<Matiereclasse> obj){
         matiereclasses = obj;
    }



}

