 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Matiereclasse")
 public class Matiereclasse {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "ecoleclasse_id")
     Integer ecoleclasse_id;
     @Column(name = "matiere_id")
     Integer matiere_id;
     @Column(name = "coefficient")
     Double coefficient;
     @Column(name = "professeur_id")
     Integer professeur_id;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getEcoleclasse_id(){
        return ecoleclasse_id;
    }


    public void setEcoleclasse_id(Integer obj){
         ecoleclasse_id = obj;
    }


    public Integer getMatiere_id(){
        return matiere_id;
    }


    public void setMatiere_id(Integer obj){
         matiere_id = obj;
    }


    public Double getCoefficient(){
        return coefficient;
    }


    public void setCoefficient(Double obj){
         coefficient = obj;
    }


    public Integer getProfesseur_id(){
        return professeur_id;
    }


    public void setProfesseur_id(Integer obj){
         professeur_id = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }



}

