 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Media")
 public class Media {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idecoleclasse")
     Integer idecoleclasse;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "titre")
     String titre;
     @Column(name = "photo")
     String photo;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdecoleclasse(){
        return idecoleclasse;
    }


    public void setIdecoleclasse(Integer obj){
         idecoleclasse = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public String getTitre(){
        return titre;
    }


    public void setTitre(String obj){
         titre = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }



}

