 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Niveau")
 public class Niveau {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "niveau")
     String niveau;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "idniveau")
     private List<Classeniveau>  classeniveaus;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getNiveau(){
        return niveau;
    }


    public void setNiveau(String obj){
         niveau = obj;
    }


    public List<Classeniveau> getClasseniveaus(){
        return classeniveaus;
    }


    public void setClasseniveaus(List<Classeniveau> obj){
         classeniveaus = obj;
    }



}

