 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Noteetudiantecole")
 public class Noteetudiantecole {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idtrimestre")
     Integer idtrimestre;
     @Column(name = "idmatiereclasse")
     Integer idmatiereclasse;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "notes")
     Double notes;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdtrimestre(){
        return idtrimestre;
    }


    public void setIdtrimestre(Integer obj){
         idtrimestre = obj;
    }


    public Integer getIdmatiereclasse(){
        return idmatiereclasse;
    }


    public void setIdmatiereclasse(Integer obj){
         idmatiereclasse = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public Double getNotes(){
        return notes;
    }


    public void setNotes(Double obj){
         notes = obj;
    }



}

