 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Parentetudiant")
 public class Parentetudiant {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "idparent")
     Integer idparent;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public Integer getIdparent(){
        return idparent;
    }


    public void setIdparent(Integer obj){
         idparent = obj;
    }



}

