 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Profil")
 public class Profil {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "profil")
     String profil;
     
    //  @OneToMany(cascade = CascadeType.ALL)
    //  @JoinColumn(name = "profil_id")
    //  private List<Users>  userss;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getProfil(){
        return profil;
    }


    public void setProfil(String obj){
         profil = obj;
    }


    // public List<Users> getUserss(){
    //     return userss;
    // }


    // public void setUserss(List<Users> obj){
    //      userss = obj;
    // }



}

