 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;

import java.beans.Transient;
import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Professeur")
 public class Professeur {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "users_id")
     Integer userId;
    @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "numtel")
     String numtel;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "professeur_id")
     private List<Matiereclasse>  matiereclasses;
     @Column(name = "matricule")
     String matricule;
     @Column(name = "photo")
     String photo;
     @Column(name = "cv")
     String cv;

     public Integer getUserId() {
        return userId;
    }


    public void setUserId(Integer userId) {
        this.userId = userId;
    }



     
     
    public String getCv() {
        return cv;
    }


    public void setCv(String cv) {
        this.cv = cv;
    }


    public String getPhoto() {
        return photo;
    }


    public void setPhoto(String photo) {
        this.photo = photo;
    }


    public String getMatricule() {
        return matricule;
    }


    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }

    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public List<Matiereclasse> getMatiereclasses(){
        return matiereclasses;
    }


    public void setMatiereclasses(List<Matiereclasse> obj){
         matiereclasses = obj;
    }



}

