 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Programmescolaire")
 public class Programmescolaire {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "datecreation")
     Date datecreation;
     @Column(name = "idmatiereclasse")
     Integer idmatiereclasse;
     @Column(name = "titre")
     String titre;
     @Column(name = "cours")
     String cours;
     @Column(name = "statut")
     Integer statut;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Date getDatecreation(){
        return datecreation;
    }


    public void setDatecreation(Date obj){
         datecreation = obj;
    }


    public Integer getIdmatiereclasse(){
        return idmatiereclasse;
    }


    public void setIdmatiereclasse(Integer obj){
         idmatiereclasse = obj;
    }


    public String getTitre(){
        return titre;
    }


    public void setTitre(String obj){
         titre = obj;
    }


    public String getCours(){
        return cours;
    }


    public void setCours(String obj){
         cours = obj;
    }


    public Integer getStatut(){
        return statut;
    }


    public void setStatut(Integer obj){
         statut = obj;
    }



}

