 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Reponseoffre")
 public class Reponseoffre {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "offreecoleid")
     Integer offreecoleid;
     @Column(name = "professeur_id")
     Integer professeur_id;
     @Column(name = "dateenvoye")
     Date dateenvoye;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getOffreecoleid(){
        return offreecoleid;
    }


    public void setOffreecoleid(Integer obj){
         offreecoleid = obj;
    }


    public Integer getProfesseur_id(){
        return professeur_id;
    }


    public void setProfesseur_id(Integer obj){
         professeur_id = obj;
    }


    public Date getDateenvoye(){
        return dateenvoye;
    }


    public void setDateenvoye(Date obj){
         dateenvoye = obj;
    }



}

