 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;
import java.sql.Time;
import java.sql.Time;
import java.sql.Time;
import java.sql.Time;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Retardeleve")
 public class Retardeleve {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idetudiantecole")
     Integer idetudiantecole;
     @Column(name = "dateretard")
     Date dateretard;
     @Column(name = "heuredebutcours")
     Time heuredebutcours;
     @Column(name = "heurearrive")
     Time heurearrive;
     @Column(name = "motif")
     String motif;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdetudiantecole(){
        return idetudiantecole;
    }


    public void setIdetudiantecole(Integer obj){
         idetudiantecole = obj;
    }


    public Date getDateretard(){
        return dateretard;
    }


    public void setDateretard(Date obj){
         dateretard = obj;
    }


    public Time getHeuredebutcours(){
        return heuredebutcours;
    }


    public void setHeuredebutcours(Time obj){
         heuredebutcours = obj;
    }


    public Time getHeurearrive(){
        return heurearrive;
    }


    public void setHeurearrive(Time obj){
         heurearrive = obj;
    }


    public String getMotif(){
        return motif;
    }


    public void setMotif(String obj){
         motif = obj;
    }



}

