 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Salaireprof")
 public class Salaireprof {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idecole")
     Integer idecole;
     @Column(name = "idecoleclasse")
     Integer idecoleclasse;
     @Column(name = "salaire")
     Double salaire;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdecole(){
        return idecole;
    }


    public void setIdecole(Integer obj){
         idecole = obj;
    }


    public Integer getIdecoleclasse(){
        return idecoleclasse;
    }


    public void setIdecoleclasse(Integer obj){
         idecoleclasse = obj;
    }


    public Double getSalaire(){
        return salaire;
    }


    public void setSalaire(Double obj){
         salaire = obj;
    }



}

