 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
import jakarta.persistence.Transient;

import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Trimestre")
 public class Trimestre {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
    @Column(name = "idecole")
     Integer idecole;
     @Column(name = "nom")
     String nom;
     @Column(name = "debuttrimestre")
     Date debuttrimestre;
     @Column(name = "fintrimestre")
     Date fintrimestre;
     @Transient
     Integer status;

     public Integer getIdanneescolaire() {
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer idanneescolaire) {
        this.idanneescolaire = idanneescolaire;
    }
     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdecole(){
        return idecole;
    }


    public void setIdecole(Integer obj){
         idecole = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public Date getDebuttrimestre(){
        return debuttrimestre;
    }


    public void setDebuttrimestre(Date obj){
         debuttrimestre = obj;
    }


    public Date getFintrimestre(){
        return fintrimestre;
    }


    public void setFintrimestre(Date obj){
         fintrimestre = obj;
    }


    public Integer getStatus() {
        return status;
    }


    public void setStatus(Integer status) {
        this.status = status;
    }



}

