 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Types")
 public class Types {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "types")
     String types;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "idtype")
     private List<Academy>  academys;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getTypes(){
        return types;
    }


    public void setTypes(String obj){
         types = obj;
    }


    public List<Academy> getAcademys(){
        return academys;
    }


    public void setAcademys(List<Academy> obj){
         academys = obj;
    }



}

