 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.util.Date;
 import java.text.ParseException;
import java.text.SimpleDateFormat;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "Users")
 public class Users {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

     @Column(name = "id")
     Integer id;
     @Column(name = "nom")
     String nom;
     @Column(name = "prenom")
     String prenom;
     @Column(name = "adresse")
     String adresse;
     @Column(name = "datenaissance")
     Date datenaissance;
     @Column(name = "adminnom")
     String adminnom;
     @Column(name = "email")
     String email;
     @Column(name = "mdp")
     String mdp;
     @Column(name = "profil_id")
     Integer profil_id;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "users_id")
     private List<Academy>  academys;
     @OneToMany(cascade = CascadeType.ALL)
     @JoinColumn(name = "users_id")
     private List<Academyusers>  academyuserss;


     
    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getPrenom(){
        return prenom;
    }


    public void setPrenom(String obj){
         prenom = obj;
    }


    public String getAdresse(){
        return adresse;
    }


    public void setAdresse(String obj){
         adresse = obj;
    }


    public Date getDatenaissance(){
        return datenaissance;
    }


    public void setDatenaissance(Date date){
         datenaissance = date;
    }


    public String getAdminnom(){
        return adminnom;
    }


    public void setAdminnom(String obj){
         adminnom = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public String getMdp(){
        return mdp;
    }


    public void setMdp(String obj){
         mdp = obj;
    }


    public Integer getProfil_id(){
        return profil_id;
    }


    public void setProfil_id(Integer obj){
         profil_id = obj;
    }


    public List<Academy> getAcademys(){
        return academys;
    }


    public void setAcademys(List<Academy> obj){
         academys = obj;
    }


    public List<Academyusers> getAcademyuserss(){
        return academyuserss;
    }


    public void setAcademyuserss(List<Academyusers> obj){
         academyuserss = obj;
    }



}

