 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_academyprof")
 public class V_academyprof {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "email")
     String email;
     @Column(name = "idacademyprof")
     Integer idacademyprof;
     @Column(name = "academyid")
     Integer academyid;
     @Column(name = "profid")
     Integer profid;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "numtel")
     String numtel;
     @Column(name = "matricule")
     String matricule;
     @Column(name = "photo")
     String photo;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public Integer getIdacademyprof(){
        return idacademyprof;
    }


    public void setIdacademyprof(Integer obj){
         idacademyprof = obj;
    }


    public Integer getAcademyid(){
        return academyid;
    }


    public void setAcademyid(Integer obj){
         academyid = obj;
    }


    public Integer getProfid(){
        return profid;
    }


    public void setProfid(Integer obj){
         profid = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public String getMatricule(){
        return matricule;
    }


    public void setMatricule(String obj){
         matricule = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }



}

