 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_demandeajoutprof")
 public class V_demandeajoutprof {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "idprof")
     Integer idprof;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "idacademy")
     Integer idacademy;
     @Column(name = "email")
     String email;
     @Column(name = "nom")
     String nom;
     @Column(name = "logo")
     String logo;
     @Column(name = "iddemandeajout")
     Integer iddemandeajout;
     @Column(name = "dateajout")
     Date dateajout;
     @Column(name = "statut")
     Integer statut;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getIdprof(){
        return idprof;
    }


    public void setIdprof(Integer obj){
         idprof = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public Integer getIdacademy(){
        return idacademy;
    }


    public void setIdacademy(Integer obj){
         idacademy = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getLogo(){
        return logo;
    }


    public void setLogo(String obj){
         logo = obj;
    }


    public Integer getIddemandeajout(){
        return iddemandeajout;
    }


    public void setIddemandeajout(Integer obj){
         iddemandeajout = obj;
    }


    public Date getDateajout(){
        return dateajout;
    }


    public void setDateajout(Date obj){
         dateajout = obj;
    }


    public Integer getStatut(){
        return statut;
    }


    public void setStatut(Integer obj){
         statut = obj;
    }



}

