 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_demandeprof")
 public class V_demandeprof {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "nomprenom")
     String nomprenom;
    @Column(name = "academy_id")
     Integer ecoleid;
     @Column(name = "iddemande")
     Integer iddemande;
     @Column(name = "cv")
     String cv;
    @Column(name = "nom")
     String nom;
     @Column(name = "adresse")
     String adresse;
     @Column(name = "description")
     String description;
     @Column(name = "numtel")
     String numtel;
     @Column(name = "email")
     String email;
     @Column(name = "logo")
     String logo;
     @Column(name = "professeur_id")
     Integer profid;
     @Column(name = "dateenvoye")
     Date dateenvoye;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "niveau")
     String niveau;
     @Column(name = "descriptions")
     String descriptions;
     @Column(name = "statut")
     Integer statut;

     
     public String getCv() {
        return cv;
    }

    public void setCv(String cv) {
        this.cv = cv;
    }

     
     public Integer getStatut() {
        return statut;
    }

    public void setStatut(Integer statut) {
        this.statut = statut;
    }

    public String getNomprenom() {
        return nomprenom;
    }

    public void setNomprenom(String nomprenom) {
        this.nomprenom = nomprenom;
    }
     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getEcoleid(){
        return ecoleid;
    }


    public void setEcoleid(Integer obj){
         ecoleid = obj;
    }


    public Integer getIddemande(){
        return iddemande;
    }


    public void setIddemande(Integer obj){
         iddemande = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getAdresse(){
        return adresse;
    }


    public void setAdresse(String obj){
         adresse = obj;
    }


    public String getDescription(){
        return description;
    }


    public void setDescription(String obj){
         description = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public String getLogo(){
        return logo;
    }


    public void setLogo(String obj){
         logo = obj;
    }


    public Integer getProfid(){
        return profid;
    }


    public void setProfid(Integer obj){
        profid = obj;
    }


    public Date getDateenvoye(){
        return dateenvoye;
    }


    public void setDateenvoye(Date obj){
         dateenvoye = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public String getNiveau(){
        return niveau;
    }


    public void setNiveau(String obj){
         niveau = obj;
    }


    public String getDescriptions(){
        return descriptions;
    }


    public void setDescriptions(String obj){
         descriptions = obj;
    }



}

