 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_ecoleclasse")
 public class V_ecoleclasse {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "ecoleclasseid")
     Integer ecoleclasseid;
     @Column(name = "idannee")
     Integer idannee;
     @Column(name = "debutanneescolaire")
     Date debutanneescolaire;
     @Column(name = "finanneescolaire")
     Date finanneescolaire;
     @Column(name = "idecole")
     Integer idecole;
     @Column(name = "iduser")
     Integer iduser;
     @Column(name = "nom")
     String nom;
     @Column(name = "adresse")
     String adresse;
     @Column(name = "description")
     String description;
     @Column(name = "idclasse")
     Integer idclasse;
     @Column(name = "classe")
     String classe;
     @Column(name = "idniveau")
     Integer idniveau;
     @Column(name = "niveau")
     String niveau;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getEcoleclasseid(){
        return ecoleclasseid;
    }


    public void setEcoleclasseid(Integer obj){
         ecoleclasseid = obj;
    }


    public Integer getIdannee(){
        return idannee;
    }


    public void setIdannee(Integer obj){
         idannee = obj;
    }


    public Date getDebutanneescolaire(){
        return debutanneescolaire;
    }


    public void setDebutanneescolaire(Date obj){
         debutanneescolaire = obj;
    }


    public Date getFinanneescolaire(){
        return finanneescolaire;
    }


    public void setFinanneescolaire(Date obj){
         finanneescolaire = obj;
    }


    public Integer getIdecole(){
        return idecole;
    }


    public void setIdecole(Integer obj){
         idecole = obj;
    }


    public Integer getIduser(){
        return iduser;
    }


    public void setIduser(Integer obj){
         iduser = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getAdresse(){
        return adresse;
    }


    public void setAdresse(String obj){
         adresse = obj;
    }


    public String getDescription(){
        return description;
    }


    public void setDescription(String obj){
         description = obj;
    }


    public Integer getIdclasse(){
        return idclasse;
    }


    public void setIdclasse(Integer obj){
         idclasse = obj;
    }


    public String getClasse(){
        return classe;
    }


    public void setClasse(String obj){
         classe = obj;
    }


    public Integer getIdniveau(){
        return idniveau;
    }


    public void setIdniveau(Integer obj){
         idniveau = obj;
    }


    public String getNiveau(){
        return niveau;
    }


    public void setNiveau(String obj){
         niveau = obj;
    }



}

