 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Time;
import java.sql.Time;
import java.sql.Time;
import java.sql.Time;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_edtclasse")
 public class V_edtclasse {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "id")
     Integer id;
     @Column(name = "classeid")
     Integer classeid;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "jour")
     String jour;
     @Column(name = "heuredebut")
     Time heuredebut;
     @Column(name = "heurefin")
     Time heurefin;
     @Column(name = "matiere")
     String matiere;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getClasseid(){
        return classeid;
    }


    public void setClasseid(Integer obj){
         classeid = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public String getJour(){
        return jour;
    }


    public void setJour(String obj){
         jour = obj;
    }


    public Time getHeuredebut(){
        return heuredebut;
    }


    public void setHeuredebut(Time obj){
         heuredebut = obj;
    }


    public Time getHeurefin(){
        return heurefin;
    }


    public void setHeurefin(Time obj){
         heurefin = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }



}

