 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import jakarta.persistence.Transient;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_infoprof")
 public class V_infoprof {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "idprofesseur")
     Integer idprofesseur;
     @Column(name = "photo")
     String photo;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "numtel")
     String numtel;
     @Column(name = "matricule")
     String matricule;
     @Column(name = "email")
     String email;    
     @Column(name = "cv")
     String cv;
    @Transient
     Integer status;

     public String getCv() {
        return cv;
    }


    public void setCv(String cv) {
        this.cv = cv;
    }


     public String getPhoto() {
        return photo;
    }


    public void setPhoto(String photo) {
        this.photo = photo;
    }
     
    public Integer getStatus() {
        return status;
    }


    public void setStatus(Integer status) {
        this.status = status;
    }


    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getIdprofesseur(){
        return idprofesseur;
    }


    public void setIdprofesseur(Integer obj){
         idprofesseur = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public String getMatricule(){
        return matricule;
    }


    public void setMatricule(String obj){
         matricule = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }



}

