 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_infoetudiant")
 public class V_infoetudiant {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "classe")
     String classe;
     @Column(name = "idecoleclasse")
     Integer idecoleclasse;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "prefixe")
     String prefixe;
     @Column(name = "nom")
     String nom;
     @Column(name = "prenom")
     String prenom;
     @Column(name = "datenaissance")
     Date datenaissance;
     @Column(name = "adresse")
     String adresse;
     @Column(name = "email")
     String email;
     @Column(name = "contact")
     String contact;
     @Column(name = "photo")
     String photo;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public String getClasse(){
        return classe;
    }


    public void setClasse(String obj){
         classe = obj;
    }


    public Integer getIdecoleclasse(){
        return idecoleclasse;
    }


    public void setIdecoleclasse(Integer obj){
         idecoleclasse = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public String getPrefixe(){
        return prefixe;
    }


    public void setPrefixe(String obj){
         prefixe = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getPrenom(){
        return prenom;
    }


    public void setPrenom(String obj){
         prenom = obj;
    }


    public Date getDatenaissance(){
        return datenaissance;
    }


    public void setDatenaissance(Date obj){
         datenaissance = obj;
    }


    public String getAdresse(){
        return adresse;
    }


    public void setAdresse(String obj){
         adresse = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public String getContact(){
        return contact;
    }


    public void setContact(String obj){
         contact = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }



}

