 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_matiereandprof")
 public class V_matiereandprof {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "id")
     Integer id;
     @Column(name = "ecoleclasse_id")
     Integer ecoleclasse_id;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "coefficient")
     double coefficient;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getEcoleclasse_id(){
        return ecoleclasse_id;
    }


    public void setEcoleclasse_id(Integer obj){
         ecoleclasse_id = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public double getCoefficient(){
        return coefficient;
    }


    public void setCoefficient(double obj){
         coefficient = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }



}

