 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_matiereclasse")
 public class V_matiereclasse {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "ecoleclasseid")
     Integer ecoleclasseid;
     @Column(name = "idmatiereclasse")
     Integer idmatiereclasse;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "idprof")
     Integer idprof;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "numtel")
     String numtel;
     @Column(name = "photo")
     String photo;
     @Column(name = "idclasse")
     Integer idclasse;
     @Column(name = "classe")
     String classe;
     @Column(name = "idmatiere")
     Integer idmatiere;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "coefficient")
     Double coefficient;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getEcoleclasseid(){
        return ecoleclasseid;
    }


    public void setEcoleclasseid(Integer obj){
         ecoleclasseid = obj;
    }


    public Integer getIdmatiereclasse(){
        return idmatiereclasse;
    }


    public void setIdmatiereclasse(Integer obj){
         idmatiereclasse = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Integer getIdprof(){
        return idprof;
    }


    public void setIdprof(Integer obj){
         idprof = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }


    public Integer getIdclasse(){
        return idclasse;
    }


    public void setIdclasse(Integer obj){
         idclasse = obj;
    }


    public String getClasse(){
        return classe;
    }


    public void setClasse(String obj){
         classe = obj;
    }


    public Integer getIdmatiere(){
        return idmatiere;
    }


    public void setIdmatiere(Integer obj){
         idmatiere = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public Double getCoefficient(){
        return coefficient;
    }


    public void setCoefficient(Double obj){
         coefficient = obj;
    }



}

