 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_moyenne")
 public class V_moyenne {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "classe")
     String classe;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "moyenne_annuelle_classe")
     Double moyenne_annuelle_classe;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public String getClasse(){
        return classe;
    }


    public void setClasse(String obj){
         classe = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Double getMoyenne_annuelle_classe(){
        return moyenne_annuelle_classe;
    }


    public void setMoyenne_annuelle_classe(Double obj){
         moyenne_annuelle_classe = obj;
    }



}

