 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_noteparannee")
 public class V_noteparannee {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "idnoteetudiantecole")
     Integer idnoteetudiantecole;
     @Column(name = "idmatiereclasse")
     Integer idmatiereclasse;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "nometudiant")
     String nometudiant;
     @Column(name = "prenom")
     String prenom;
     @Column(name = "idtrimestre")
     Integer idtrimestre;
     @Column(name = "nom")
     String nom;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "coefficient")
     Double coefficient;
     @Column(name = "notes")
     Double notes;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getIdnoteetudiantecole(){
        return idnoteetudiantecole;
    }


    public void setIdnoteetudiantecole(Integer obj){
         idnoteetudiantecole = obj;
    }


    public Integer getIdmatiereclasse(){
        return idmatiereclasse;
    }


    public void setIdmatiereclasse(Integer obj){
         idmatiereclasse = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public String getNometudiant(){
        return nometudiant;
    }


    public void setNometudiant(String obj){
         nometudiant = obj;
    }


    public String getPrenom(){
        return prenom;
    }


    public void setPrenom(String obj){
         prenom = obj;
    }


    public Integer getIdtrimestre(){
        return idtrimestre;
    }


    public void setIdtrimestre(Integer obj){
         idtrimestre = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public Double getCoefficient(){
        return coefficient;
    }


    public void setCoefficient(Double obj){
         coefficient = obj;
    }


    public Double getNotes(){
        return notes;
    }


    public void setNotes(Double obj){
         notes = obj;
    }



}

