 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_parentetudiant")
 public class V_parentetudiant {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "parentemail")
     String parentemail;
     @Column(name = "idparent")
     Integer idparent;
     @Column(name = "idetudiant")
     Integer idetudiant;
     @Column(name = "nom")
     String nom;
     @Column(name = "prenom")
     String prenom;
     @Column(name = "photo")
     String photo;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public String getParentemail(){
        return parentemail;
    }


    public void setParentemail(String obj){
         parentemail = obj;
    }


    public Integer getIdparent(){
        return idparent;
    }


    public void setIdparent(Integer obj){
         idparent = obj;
    }


    public Integer getIdetudiant(){
        return idetudiant;
    }


    public void setIdetudiant(Integer obj){
         idetudiant = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getPrenom(){
        return prenom;
    }


    public void setPrenom(String obj){
         prenom = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }



}

