 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_profilprof")
 public class V_profilprof {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "iduser")
     Integer iduser;
     @Column(name = "idprofesseur")
     Integer idprofesseur;
     @Column(name = "nom")
     String nom;
     @Column(name = "prenom")
     String prenom;
     @Column(name = "datenaissance")
     Date datenaissance;
     @Column(name = "adresse")
     String adresse;
     @Column(name = "email")
     String email;
     @Column(name = "mdp")
     String mdp;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "numtel")
     String numtel;
     @Column(name = "cv")
     String cv;
     @Column(name = "photo")
     String photo;
     @Column(name = "matricule")
     String matricule;
     @Column(name = "adminnom")
     String adminnom;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getIduser(){
        return iduser;
    }


    public void setIduser(Integer obj){
         iduser = obj;
    }


    public Integer getIdprofesseur(){
        return idprofesseur;
    }


    public void setIdprofesseur(Integer obj){
         idprofesseur = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getPrenom(){
        return prenom;
    }


    public void setPrenom(String obj){
         prenom = obj;
    }


    public Date getDatenaissance(){
        return datenaissance;
    }


    public void setDatenaissance(Date obj){
         datenaissance = obj;
    }


    public String getAdresse(){
        return adresse;
    }


    public void setAdresse(String obj){
         adresse = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public String getMdp(){
        return mdp;
    }


    public void setMdp(String obj){
         mdp = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public String getCv(){
        return cv;
    }


    public void setCv(String obj){
         cv = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }


    public String getMatricule(){
        return matricule;
    }


    public void setMatricule(String obj){
         matricule = obj;
    }


    public String getAdminnom(){
        return adminnom;
    }


    public void setAdminnom(String obj){
         adminnom = obj;
    }



}

