 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import jakarta.persistence.Transient;
 

 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_profnotinacademy")
 public class V_profnotinacademy {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "photo")
     String photo;
     @Column(name = "classe")
     String classe;
     @Column(name = "email")
     String email;
     @Column(name = "academyid")
     Integer academyid;
     @Column(name = "idprof")
     Integer idprof;
     @Column(name = "matricule")
     String matricule;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "numtel")
     String numtel;
     @Column(name = "cv")
     String cv;
     @Transient
     Integer status;


     
    public Integer getStatus() {
        return status;
    }


    public void setStatus(Integer status) {
        this.status = status;
    }


    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public String getPhoto(){
        return photo;
    }


    public void setPhoto(String obj){
         photo = obj;
    }


    public String getClasse(){
        return classe;
    }


    public void setClasse(String obj){
         classe = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public Integer getAcademyid(){
        return academyid;
    }


    public void setAcademyid(Integer obj){
         academyid = obj;
    }


    public Integer getIdprof(){
        return idprof;
    }


    public void setIdprof(Integer obj){
         idprof = obj;
    }


    public String getMatricule(){
        return matricule;
    }


    public void setMatricule(String obj){
         matricule = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public String getNumtel(){
        return numtel;
    }


    public void setNumtel(String obj){
         numtel = obj;
    }


    public String getCv(){
        return cv;
    }


    public void setCv(String obj){
         cv = obj;
    }



}

