 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_reponseoffre")
 public class V_reponseoffre {
     @Id
     
     @Column(name = "row_num")
     int row_num;
     @Column(name = "id")
     Integer id;
     @Column(name = "professeur_id")
     Integer profid;
     @Column(name = "nom")
     String nom;
     @Column(name = "poste")
     String poste;
     @Column(name = "descriptions")
     String descriptions;
     @Column(name = "dateenvoye")
     Date dateenvoye;


     
    public int getRow_num(){
        return row_num;
    }


    public void setRow_num(int obj){
         row_num = obj;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getProfid(){
        return profid;
    }


    public void setProfid(Integer obj){
         profid = obj;
    }


    public String getNom(){
        return nom;
    }


    public void setNom(String obj){
         nom = obj;
    }


    public String getPoste(){
        return poste;
    }


    public void setPoste(String obj){
         poste = obj;
    }


    public String getDescriptions(){
        return descriptions;
    }


    public void setDescriptions(String obj){
         descriptions = obj;
    }


    public Date getDateenvoye(){
        return dateenvoye;
    }


    public void setDateenvoye(Date obj){
         dateenvoye = obj;
    }



}

