 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_salaireparannee")
 public class V_salaireparannee {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "debutanneescolaire")
     Date debutanneescolaire;
     @Column(name = "finanneescolaire")
     Date finanneescolaire;
     @Column(name = "id")
     Integer id;
     @Column(name = "idacademy")
     Integer idacademy;
     @Column(name = "profid")
     Integer profid;
     @Column(name = "nombre_de_fois")
     Integer nombre_de_fois;
     @Column(name = "total_heures")
     Double total_heures;
     @Column(name = "salaire")
     Double salaire;
     @Column(name = "difference_mois")
     Double difference_mois;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Date getDebutanneescolaire(){
        return debutanneescolaire;
    }


    public void setDebutanneescolaire(Date obj){
         debutanneescolaire = obj;
    }


    public Date getFinanneescolaire(){
        return finanneescolaire;
    }


    public void setFinanneescolaire(Date obj){
         finanneescolaire = obj;
    }


    public Integer getId(){
        return id;
    }


    public void setId(Integer obj){
         id = obj;
    }


    public Integer getIdacademy(){
        return idacademy;
    }


    public void setIdacademy(Integer obj){
         idacademy = obj;
    }


    public Integer getProfid(){
        return profid;
    }


    public void setProfid(Integer obj){
         profid = obj;
    }


    public Integer getNombre_de_fois(){
        return nombre_de_fois;
    }


    public void setNombre_de_fois(Integer obj){
         nombre_de_fois = obj;
    }


    public Double getTotal_heures(){
        return total_heures;
    }


    public void setTotal_heures(Double obj){
         total_heures = obj;
    }


    public Double getSalaire(){
        return salaire;
    }


    public void setSalaire(Double obj){
         salaire = obj;
    }


    public Double getDifference_mois(){
        return difference_mois;
    }


    public void setDifference_mois(Double obj){
         difference_mois = obj;
    }



}

