 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_totalsalairepannee")
 public class V_totalsalairepannee {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "idanneescolaire")
     Integer idanneescolaire;
     @Column(name = "debutanneescolaire")
     Date debutanneescolaire;
     @Column(name = "finanneescolaire")
     Date finanneescolaire;
     @Column(name = "profid")
     Integer profid;
     @Column(name = "total_final")
     Double total_final;


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Integer getIdanneescolaire(){
        return idanneescolaire;
    }


    public void setIdanneescolaire(Integer obj){
         idanneescolaire = obj;
    }


    public Date getDebutanneescolaire(){
        return debutanneescolaire;
    }


    public void setDebutanneescolaire(Date obj){
         debutanneescolaire = obj;
    }


    public Date getFinanneescolaire(){
        return finanneescolaire;
    }


    public void setFinanneescolaire(Date obj){
         finanneescolaire = obj;
    }


    public Integer getProfid(){
        return profid;
    }


    public void setProfid(Integer obj){
         profid = obj;
    }


    public Double getTotal_final(){
        return total_final;
    }


    public void setTotal_final(Double obj){
         total_final = obj;
    }



}

