 package com.spring.model;

 import jakarta.persistence.CascadeType;
 import jakarta.persistence.JoinColumn;
 import jakarta.persistence.OneToMany;
 import java.util.List;
 import jakarta.persistence.Column;
 import jakarta.persistence.Entity;
 import jakarta.persistence.GeneratedValue;
 import jakarta.persistence.GenerationType;
 import jakarta.persistence.Id;
 import jakarta.persistence.Table;
 import java.sql.Date;
import java.sql.Date;


 /*
    File generated By
    Christooj_Generation_Code
 */
 @Entity
 @Table(name = "V_voirdemande")
 public class V_voirdemande {
     @Id
     
     @Column(name = "row_num")
     Integer row_num;
     @Column(name = "demandeid")
     Integer demandeid;
     @Column(name = "dateenvoye")
     Date dateenvoye;
     @Column(name = "ecole_id")
     Integer ecoleId;
     @Column(name = "professeur_id")
     Integer professeur_id;
     @Column(name = "nomprenom")
     String nomprenom;
     @Column(name = "email")
     String email;
     @Column(name = "matiere")
     String matiere;
     @Column(name = "niveau")
     String niveau;
     @Column(name = "descriptions")
     String descriptions;
     @Column(name = "cv")
     String cv;
    
     public Integer getDemandeId(){
        return demandeid;
     }

     public void setDemandeId(Integer obj){
        demandeid = obj;
     }


     
    public Integer getRow_num(){
        return row_num;
    }


    public void setRow_num(Integer obj){
         row_num = obj;
    }


    public Date getDateenvoye(){
        return dateenvoye;
    }


    public void setDateenvoye(Date obj){
         dateenvoye = obj;
    }


    public Integer getEcoleId(){
        return ecoleId;
    }


    public void setEcoleId(Integer obj){
         ecoleId = obj;
    }


    public Integer getProfesseur_id(){
        return professeur_id;
    }


    public void setProfesseur_id(Integer obj){
         professeur_id = obj;
    }


    public String getNomprenom(){
        return nomprenom;
    }


    public void setNomprenom(String obj){
         nomprenom = obj;
    }


    public String getEmail(){
        return email;
    }


    public void setEmail(String obj){
         email = obj;
    }


    public String getMatiere(){
        return matiere;
    }


    public void setMatiere(String obj){
         matiere = obj;
    }


    public String getNiveau(){
        return niveau;
    }


    public void setNiveau(String obj){
         niveau = obj;
    }


    public String getDescriptions(){
        return descriptions;
    }


    public void setDescriptions(String obj){
         descriptions = obj;
    }


    public String getCv(){
        return cv;
    }


    public void setCv(String obj){
         cv = obj;
    }



}

