package com.spring.utility;


import java.lang.reflect.Field;
import java.lang.reflect.Method;

/*
   File generated By
   Christooj_Generation_Code
*/
public class Utilitaire {


   public static String capitalize(String str) {
       return str.substring(0, 1).toUpperCase() + str.substring(1);
   }

   public static Object addValueObject(Object source,Object nouveau)throws Exception{
           Field[] fields = source.getClass().getDeclaredFields();
           for (Field fd : fields) {
               Method meth_nouveau = nouveau.getClass().getMethod("get"+capitalize(fd.getName()));
               if(meth_nouveau.invoke(nouveau) != null){
                   Object value = meth_nouveau.invoke(nouveau);
                   Method meth_source = source.getClass().getMethod("set"+capitalize(fd.getName()),fd.getType());
                   meth_source.invoke(source,value);
               }
           }
           return source;
       }

}

